### ISSUE TITLE
Replica pod fails to start

### ISSUE THREAD

**Issue by MohamedMSaeed** [zalando/postgres-operator#1113]
Hello folks,

I have created a cluster of a master and one replica, the replica suddenly failed and refused to start again. I restarted the pod several times but it didn't start. 

postgres-operator version `1.5.0`

I found the following logs in master

```
2020-08-20 18:20:02,454 ERROR: ObjectCache.run MaxRetryError("HTTPSConnectionPool(host='10.23.240.1', port=443): Max retries exceeded with url: /api/v1/namespaces/team-db-pgo/endpoints?labelSelector=environment%3Ddev%2Cdev%3Dteam-db (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b3c05a0f0>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2020-08-20 18:20:02,456 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b3c05ab70>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/team-db-pgo/endpoints?labelSelector=environment%3Ddev%2Cdev%3Dteam-db
2020-08-20 18:20:02,456 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b3c05abe0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/team-db-pgo/pods?labelSelector=environment%3Ddev%2Cdev%3Dteam-db
2020-08-20 18:20:02,457 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b3eadc240>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/team-db-pgo/endpoints?labelSelector=environment%3Ddev%2Cdev%3Dteam-db
2020-08-20 18:20:02,458 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b3eadc048>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/team-db-pgo/pods?labelSelector=environment%3Ddev%2Cdev%3Dteam-db
2020-08-20 18:20:02,458 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b3eadc588>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/team-db-pgo/endpoints?labelSelector=environment%3Ddev%2Cdev%3Dteam-db
2020-08-20 18:20:03,136 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b3ca8d080>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/team-db-pgo/pods?labelSelector=environment%3Ddev%2Cdev%3Dteam-db
2020-08-20 18:20:03,459 ERROR: ObjectCache.run MaxRetryError("HTTPSConnectionPool(host='10.23.240.1', port=443): Max retries exceeded with url: /api/v1/namespaces/team-db-pgo/endpoints?labelSelector=environment%3Ddev%2Cdev%3Dteam-db (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b3caa35f8>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2020-08-20 18:20:04,137 ERROR: ObjectCache.run MaxRetryError("HTTPSConnectionPool(host='10.23.240.1', port=443): Max retries exceeded with url: /api/v1/namespaces/team-db-pgo/pods?labelSelector=environment%3Ddev%2Cdev%3Dteam-db (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b3caa34e0>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2020-08-20 18:20:10,219 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 498, in _load_cluster
    self._wait_caches()
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 492, in _wait_caches
    raise RetryFailedError('Exceeded retry deadline')
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2020-08-20 18:20:10,219 ERROR: Error communicating with DCS
2020-08-20 18:20:10,221 INFO: DCS is not accessible
2020-08-20 18:20:10,222 WARNING: Loop time exceeded, rescheduling immediately.
2020-08-20 18:20:13,470 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b1e799470>, 'Connection to 10.23.240.1 timed out. (connect timeout=10)')': /api/v1/namespaces/team-db-pgo/endpoints?labelSelector=environment%3Ddev%2Cdev%3Dteam-db
2020-08-20 18:20:14,148 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b1e799240>, 'Connection to 10.23.240.1 timed out. (connect timeout=10)')': /api/v1/namespaces/team-db-pgo/pods?labelSelector=environment%3Ddev%2Cdev%3Dteam-db
2020-08-20 18:20:20,222 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 498, in _load_cluster
    self._wait_caches()
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 492, in _wait_caches
    raise RetryFailedError('Exceeded retry deadline')
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2020-08-20 18:20:20,223 ERROR: Error communicating with DCS
2020-08-20 18:20:20,224 INFO: DCS is not accessible
2020-08-20 18:20:20,226 WARNING: Loop time exceeded, rescheduling immediately.
2020-08-20 18:20:23,480 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b1e799668>, 'Connection to 10.23.240.1 timed out. (connect timeout=10)')': /api/v1/namespaces/team-db-pgo/endpoints?labelSelector=environment%3Ddev%2Cdev%3Dteam-db
2020-08-20 18:20:24,159 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3b1e7998d0>, 'Connection to 10.23.240.1 timed out. (connect timeout=10)')': /api/v1/namespaces/team-db-pgo/pods?labelSelector=environment%3Ddev%2Cdev%3Dteam-db
2020-08-20 18:20:24.524 25 LOG {ticks: 0, maint: 0, retry: 0}
2020-08-20 18:20:30,226 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 498, in _load_cluster
    self._wait_caches()
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 492, in _wait_caches
    raise RetryFailedError('Exceeded retry deadline')
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
```

After while logs became like this..
```

2020-08-20 19:18:20,416 INFO: no action.  i am the leader with the lock
2020-08-20 19:18:26.360 25 LOG {ticks: 0, maint: 0, retry: 0}
2020-08-20 19:18:30,361 INFO: Lock owner: team-db-0; I am team-db-0
2020-08-20 19:18:30,408 INFO: no action.  i am the leader with the lock
2020-08-20 19:18:40,361 INFO: Lock owner: team-db-0; I am team-db-0
```

Replica logs

```
2020-08-20 20:04:52,995 INFO: Lock owner: team-db-0; I am team-db-1
2020-08-20 20:04:53,016 INFO: Local timeline=9 lsn=1/6B000098
2020-08-20 20:04:53,028 INFO: master_timeline=11
2020-08-20 20:04:53,029 INFO: master: history=1	0/7000098	no recovery target specified

2	0/28000098	no recovery target specified

3	0/68000000	no recovery target specified

4	0/78000098	no recovery target specified

5	0/820361C0	no recovery target specified

6	1/3C000098	no recovery target specified

7	1/4E000098	no recovery target specified

8	1/6A000098	no recovery target specified

9	1/91000000	no recovery target specified

10	1/93000098	no recovery target specified

2020-08-20 20:04:53,029 INFO: Lock owner: team-db-0; I am team-db-1
2020-08-20 20:04:53,030 INFO: starting as a secondary
2020-08-20 20:04:53 UTC [1679]: [1-1] 5f3ed765.68f 0     LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...
2020-08-20 20:04:53 UTC [1679]: [2-1] 5f3ed765.68f 0     LOG:  pg_stat_kcache.linux_hz is set to 1000000
2020-08-20 20:04:53 UTC [1679]: [3-1] 5f3ed765.68f 0     LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-08-20 20:04:53 UTC [1679]: [4-1] 5f3ed765.68f 0     LOG:  listening on IPv6 address "::", port 5432
2020-08-20 20:04:53 UTC [1679]: [5-1] 5f3ed765.68f 0     LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-08-20 20:04:53,441 INFO: postmaster pid=1679
2020-08-20 20:04:53 UTC [1679]: [6-1] 5f3ed765.68f 0     LOG:  redirecting log output to logging collector process
2020-08-20 20:04:53 UTC [1679]: [7-1] 5f3ed765.68f 0     HINT:  Future log output will appear in directory "../pg_log".
/var/run/postgresql:5432 - rejecting connections
/var/run/postgresql:5432 - rejecting connections
/var/run/postgresql:5432 - rejecting connections
/var/run/postgresql:5432 - no response
2020-08-20 20:04:55,505 INFO: Lock owner: team-db-0; I am team-db-1
2020-08-20 20:04:55,505 INFO: failed to start postgres
2020-08-20 20:05:05,505 WARNING: Postgresql is not running.
2020-08-20 20:05:05,505 INFO: Lock owner: team-db-0; I am team-db-1
2020-08-20 20:05:05,510 INFO: pg_controldata:
  pg_control version number: 1100
  Catalog version number: 201809051
  Database system identifier: 6850021030552608835
  Database cluster state: shut down in recovery
  pg_control last modified: Thu Aug 20 18:19:18 2020
  Latest checkpoint location: 1/6B000028
  Latest checkpoint's REDO location: 1/6B000028
  Latest checkpoint's REDO WAL file: 00000009000000010000006B
  Latest checkpoint's TimeLineID: 9
  Latest checkpoint's PrevTimeLineID: 9
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:5070
  Latest checkpoint's NextOID: 34641
  Latest checkpoint's NextMultiXactId: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint's oldestXID: 562
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestActiveXID: 0
  Latest checkpoint's oldestMultiXid: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Mon Aug 17 12:35:40 2020
  Fake LSN counter for unlogged rels: 0/1
  Minimum recovery ending location: 1/6B000098
  Min recovery ending loc's timeline: 9
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: replica
  wal_log_hints setting: on
  max_connections setting: 250
  max_worker_processes setting: 8
  max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float4 argument passing: by value
  Float8 argument passing: by value
  Data page checksum version: 1
  Mock authentication nonce: 7b1109a4f29e55d66ac0e9fac32068015ed20d971a047675212ec9b4fb2cdf88
```

I also tried to exec tha replica pod and connect to postgres server but it gave me this error "which means the server is not up"
```
# psql
psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

It is worth mentioning that `service --status-all` shows that `pgqd` is not started! while in master it is up. 
```
# service --status-all
 [ - ]  cron
 [ ? ]  hwclock.sh
 [ - ]  pgbouncer
 [ - ]  pgqd
 [ - ]  postgresql
 [ - ]  procps
```

Can you help, please?

**Comment by Jan-M** [comment]
Essentially without being able to communicate with DCS (K8s API) it will not elect and fix anything. You should focus on resolving this first.

What environment and setup are you running on?

Check that you have pod and operator service accounts and rbac properly applied and that spilo says it uses kubernetes for leader election.
