### ISSUE TITLE
UI cant auth with kubernetes

### ISSUE THREAD

**Issue by yannick** [zalando/postgres-operator#1143]
- **Which image of the operator are you using?** e.g. 
registry.opensource.zalan.do/acid/postgres-operator-ui:v1.5.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
AWS
- **Are you running Postgres Operator in production?** [yes | no]
yes
- **Type of issue?** [Bug report, question, feature request, etc.]
UI seems not to be able to auth with K8s endpoint:

```
Client Error: Forbidden for url: https://172.16.0.1:443/apis/acid.zalan.do/v1/namespaces/db/postgresqls
```

detailed:
```
operator_ui.main ERROR    Exception on /postgresqls [GET]
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
            response = self.full_dispatch_request()
          File "/usr/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
            rv = self.handle_user_exception(e)
          File "/usr/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
            reraise(exc_type, exc_value, tb)
          File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
            raise value
          File "/usr/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
            rv = self.dispatch_request()
          File "/usr/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
            return self.view_functions[rule.endpoint](**req.view_args)
          File "/operator_ui/main.py", line 193, in wrapper
            return f(*args, **kwargs)
          File "/operator_ui/main.py", line 501, in get_postgresqls
            else TARGET_NAMESPACE
          File "/operator_ui/spiloutils.py", line 209, in read_postgresqls
            namespace=namespace,
          File "/operator_ui/spiloutils.py", line 143, in kubernetes_get
            response.raise_for_status()
          File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
            raise HTTPError(http_error_msg, response=self)
        requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://172.16.0.1:443/apis/acid.zalan.do/v1/namespaces/db/postgresqls
```

**Comment by FxKu** [comment]
Have you also deployed the [service account and RBAC](https://github.com/zalando/postgres-operator/blob/master/ui/manifests/ui-service-account-rbac.yaml) for the UI?
