### ISSUE TITLE
configmaps "postgres-operator" is forbidden

### ISSUE THREAD

**Issue by softshipper** [zalando/postgres-operator#1181]
Hi all 

 I am trying to install postgres-operator 1.5.0 on my K8S cluster version 1.18.8-do.1 DigitalOcean and I have got the following error message:

```
2020/10/21 08:33:39 Fully qualified configmap name: postgres/postgres-operator
2020/10/21 08:33:39 Spilo operator v1.5.0-dirty
panic: configmaps "postgres-operator" is forbidden: User "system:serviceaccount:postgres:postgres-operator" cannot get resource "configmaps" in API group "" in the namespace "postgres"
goroutine 1 [running]:
github.com/zalando/postgres-operator/pkg/controller.(*Controller).initOperatorConfig(0xc0000de000)
  /home/fekunde/go/src/github.com/zalando/postgres-operator/pkg/controller/controller.go:124 +0x650
github.com/zalando/postgres-operator/pkg/controller.(*Controller).initController(0xc0000de000)
  /home/fekunde/go/src/github.com/zalando/postgres-operator/pkg/controller/controller.go:282 +0x8a2
github.com/zalando/postgres-operator/pkg/controller.(*Controller).Run(0xc0000de000, 0xc000102cc0, 0xc0000a6000)
  /home/fekunde/go/src/github.com/zalando/postgres-operator/pkg/controller/controller.go:377 +0x2f
main.main()
  /home/fekunde/go/src/github.com/zalando/postgres-operator/cmd/main.go:82 +0x25e
```
I have deployed the operator with the following commands:
```
# First, clone the repository and change to the directory
git clone https://github.com/zalando/postgres-operator.git
cd postgres-operator

# apply the manifests in the following order
kubectl create -f manifests/configmap.yaml  # configuration
kubectl create -f manifests/operator-service-account-rbac.yaml  # identity and permissions
kubectl create -f manifests/postgres-operator.yaml  # deployment
kubectl create -f manifests/api-service.yaml  # operator API to be used by UI
```

What am I doing wrong?  

Thanks

**Comment by Jan-M** [comment]
Likely you lack proper privileges for your pod to read configmap? check with the rbac manifests provided.
