### ISSUE TITLE
Clone (restore) from GCS using WAL-G results in an unexpected error

### ISSUE THREAD

**Issue by boonen** [zalando/postgres-operator#1201]
I'm testing the backup and restore functionality of the Postgres Operator (`v1.5.0`) on Kubernetes (GKE). WAL backups are correctly written to my GCS bucket, but a restore (complete new cluster) using the Patroni clone method does not work. The backup files are downloaded in the Pod which should restore the cluster, but when importing the WAL files the postgres Pod show the following error:

```
2020-11-06 21:31:40,703 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
2020-11-06 21:31:40,729 - bootstrapping - INFO - Looks like your running google
2020-11-06 21:31:40,769 - bootstrapping - INFO - Configuring pgbouncer
2020-11-06 21:31:40,769 - bootstrapping - INFO - No PGBOUNCER_CONFIGURATION was specified, skipping
2020-11-06 21:31:40,769 - bootstrapping - INFO - Configuring patroni
2020-11-06 21:31:40,789 - bootstrapping - INFO - Writing to file /home/postgres/postgres.yml
2020-11-06 21:31:40,789 - bootstrapping - INFO - Configuring standby-cluster
2020-11-06 21:31:40,790 - bootstrapping - INFO - Configuring certificate
2020-11-06 21:31:40,790 - bootstrapping - INFO - Generating ssl certificate
2020-11-06 21:31:40,893 - bootstrapping - INFO - Configuring pam-oauth2
2020-11-06 21:31:40,894 - bootstrapping - INFO - No PAM_OAUTH2 configuration was specified, skipping
2020-11-06 21:31:40,894 - bootstrapping - INFO - Configuring crontab
2020-11-06 21:31:40,894 - bootstrapping - INFO - Skipping creation of renice cron job due to lack of SYS_NICE capability
2020-11-06 21:31:40,908 - bootstrapping - INFO - Configuring bootstrap
2020-11-06 21:31:40,909 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env-clone-cluster-backup/WALE_GS_PREFIX
2020-11-06 21:31:40,909 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env-clone-cluster-backup/WALG_GS_PREFIX
2020-11-06 21:31:40,909 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env-clone-cluster-backup/GOOGLE_APPLICATION_CREDENTIALS
2020-11-06 21:31:40,910 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env-clone-cluster-backup/USE_WALG_BACKUP
2020-11-06 21:31:40,910 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env-clone-cluster-backup/USE_WALG_RESTORE
2020-11-06 21:31:40,910 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env-clone-cluster-backup/WALE_LOG_DESTINATION
2020-11-06 21:31:40,910 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env-clone-cluster-backup/TMPDIR
2020-11-06 21:31:40,911 - bootstrapping - INFO - Configuring log
2020-11-06 21:31:40,911 - bootstrapping - INFO - Configuring wal-e
2020-11-06 21:31:40,911 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALE_GS_PREFIX
2020-11-06 21:31:40,911 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_GS_PREFIX
2020-11-06 21:31:40,911 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/GOOGLE_APPLICATION_CREDENTIALS
2020-11-06 21:31:40,912 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_DOWNLOAD_CONCURRENCY
2020-11-06 21:31:40,912 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_UPLOAD_CONCURRENCY
2020-11-06 21:31:40,912 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/USE_WALG_BACKUP
2020-11-06 21:31:40,912 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/USE_WALG_RESTORE
2020-11-06 21:31:40,913 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALE_LOG_DESTINATION
2020-11-06 21:31:40,913 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/BACKUP_NUM_TO_RETAIN
2020-11-06 21:31:40,913 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/TMPDIR
2020-11-06 21:31:40,913 - bootstrapping - INFO - Configuring pgqd
2020-11-06 21:31:42,458 INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-11-06 21:31:42,465 INFO: Lock owner: None; I am postgres-cluster-restore-0
2020-11-06 21:31:42,592 INFO: trying to bootstrap a new cluster
2020-11-06 21:31:42,592 INFO: Running custom bootstrap script: envdir "/run/etc/wal-e.d/env-clone-postgres-cluster-backup" python3 /scripts/clone_with_wale.py --recovery-target-time="2020-11-06T14:20:33+01:00"
2020-11-06 21:31:42,982 INFO: cloning cluster postgres-cluster-restore using wal-g backup-fetch /home/postgres/pgdata/pgroot/data base_000000050000000000000013
INFO: 2020/11/06 21:31:43.664747 Finished decompression of part_003.tar.lz4
INFO: 2020/11/06 21:31:43.664769 Finished extraction of part_003.tar.lz4
INFO: 2020/11/06 21:31:47.385293 Finished decompression of part_001.tar.lz4
INFO: 2020/11/06 21:31:47.385351 Finished extraction of part_001.tar.lz4
INFO: 2020/11/06 21:31:47.440566 Finished decompression of pg_control.tar.lz4
INFO: 2020/11/06 21:31:47.440591 Finished extraction of pg_control.tar.lz4
INFO: 2020/11/06 21:31:47.440600
Backup extraction complete.
2020-11-06 21:31:47,694 maybe_pg_upgrade INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-11-06 21:31:48 UTC [100]: [1-1] 5fa5c0c4.64 0     LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...
2020-11-06 21:31:48 UTC [100]: [2-1] 5fa5c0c4.64 0     LOG:  pg_stat_kcache.linux_hz is set to 333333
2020-11-06 21:31:48 UTC [100]: [3-1] 5fa5c0c4.64 0     LOG:  starting PostgreSQL 12.4 (Ubuntu 12.4-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
2020-11-06 21:31:48 UTC [100]: [4-1] 5fa5c0c4.64 0     LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-11-06 21:31:48 UTC [100]: [5-1] 5fa5c0c4.64 0     LOG:  listening on IPv6 address "::", port 5432
2020-11-06 21:31:48,032 INFO: postmaster pid=100
/var/run/postgresql:5432 - no response
2020-11-06 21:31:48 UTC [100]: [6-1] 5fa5c0c4.64 0     LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-11-06 21:31:48 UTC [100]: [7-1] 5fa5c0c4.64 0     LOG:  redirecting log output to logging collector process
2020-11-06 21:31:48 UTC [100]: [8-1] 5fa5c0c4.64 0     HINT:  Future log output will appear in directory "../pg_log".
/var/run/postgresql:5432 - rejecting connections
/var/run/postgresql:5432 - rejecting connections
/var/run/postgresql:5432 - no response
2020-11-06 21:31:50,123 INFO: removing initialize key after failed attempt to bootstrap the cluster
2020-11-06 21:31:50,172 INFO: renaming data directory to /home/postgres/pgdata/pgroot/data_2020-11-06-21-31-50
2020-11-06 21:31:50,228 ERROR: Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1385, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1288, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1184, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1179, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
2020-11-06 21:31:50,228 INFO: Unexpected exception raised, please report it as a BUG
2020-11-06 21:31:50,229 ERROR: Exception when saving file: /home/postgres/pgdata/pgroot/data/patroni.dynamic.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/config.py", line 140, in save_cache
    (fd, tmpfile) = tempfile.mkstemp(prefix=self.__CACHE_FILENAME, dir=self._data_dir)
  File "/usr/lib/python3.6/tempfile.py", line 483, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.6/tempfile.py", line 401, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/home/postgres/pgdata/pgroot/data/patroni.dynamic.json08fguyi3'
2020-11-06 21:32:00,624 INFO: removing initialize key after failed attempt to bootstrap the cluster
```

The Postgres Operator is configured using the following `ConfigMap` with WAL configurations:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator-pod-config
  namespace: operators
data:
  BACKUP_NUM_TO_RETAIN: "3"
  BACKUP_SCHEDULE: 0 12 * * *
  CLONE_BACKUP_NUM_TO_RETAIN: "3"
  CLONE_BACKUP_SCHEDULE: 0 12 * * *
  CLONE_GOOGLE_APPLICATION_CREDENTIALS: /gcs/GOOGLE_SERVICE_ACCOUNT_JSON_KEY
  CLONE_USE_WALG_BACKUP: "true"
  CLONE_USE_WALG_RESTORE: "true"
  CLONE_WALE_BACKUP_THRESHOLD_PERCENTAGE: "100"
  CLONE_WALG_GS_PREFIX: gs://cluster-backup/$(CLONE_SCOPE)
  GOOGLE_APPLICATION_CREDENTIALS: /gcs/GOOGLE_SERVICE_ACCOUNT_JSON_KEY
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  WALE_BACKUP_THRESHOLD_PERCENTAGE: "100"
  WALG_GS_PREFIX: gs://cluster-backup/$(SCOPE)
```

The cluster to which I want to restore the WAL backup is created using the following manifest:

```yaml
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: psotgres-cluster-restore
spec:
  clone:
    cluster: postgres-cluster-backup
    timestamp: "2020-11-06T14:20:33+01:00"
  numberOfInstances: 2
  postgresql:
    version: "12"
```

Can anyone tell me whether I have ran into a bug or whether I have made a mistake in my configuration?

**Comment by boonen** [comment]
UPDATE: the restore of another Postgres cluster on the same GKE environment - which uses the same operator - the restore went perfectly smooth. I can't find any changes in my configuration or manifests, so I presume this was a 'one-off' error. I will close the issue for now.
