### ISSUE TITLE
update leader lock errors --> upgrade to patroni 2.01

### ISSUE THREAD

**Issue by Reinhard-F** [zalando/postgres-operator#1332]
Hi at all,
we have problems with the availability of our Postgres database in the cluster. The error message is: failed to update leader lock. This problem has apparently been fixed in version 2.01 of Patron. See:
https://github.com/zalando/patroni/blob/master/docs/releases.rst#version-201
https://github.com/zalando/patroni/issues/1589
Is there already a point in time when Patroni version 2.01 will be integrated?

Thanks for response!

**Comment by CyberDem0n** [comment]
Hi @Reinhard-F, you didn't specify which spilo image is used.
The latest `spilo-13` already contains Patroni 2.0.1 and a few patches on top.

**Comment by Reinhard-F** [comment]
Thanks a lot for your answer.
We are using spile version ffspilo-12:1.6p

I try to upgrade this. Should i use version spilo-13:2.0-p2, described here: https://github.com/zalando/postgres-operator#notes-on-postgres-13-support

**Comment by CyberDem0n** [comment]
You better you the latest one: https://github.com/zalando/spilo/releases

**Comment by Reinhard-F** [comment]
Many thanks for your support. It seems to be working. I will continue to watch this, but I am confident ...
Thanks!

**Comment by Reinhard-F** [comment]
Update on "failed to update leader lock".
I made the following changes:
Build a Docker image with the Spilo version 2.0-p3
Change ttl and retry_timeout (ttl: 60, retry_timeout: 20)
"curl -s localhost: 8008 / config | jq." provides the following values:
{
  "loop_wait": 10,
  "maximum_lag_on_failover": 33554432,
  "postgresql": {
    "parameters": {
      "archive_mode": "on",
      "archive_timeout": "1800s",
      "autovacuum_analyze_scale_factor": 0.02,
      "autovacuum_max_workers": 5,
      "autovacuum_vacuum_scale_factor": 0.05,
      "checkpoint_completion_target": 0.9,
      "hot_standby": "on",
      "log_autovacuum_min_duration": 0,
      "log_checkpoints": "on",
      "log_connections": "on",
      "log_disconnections": "on",
      "log_line_prefix": "% t [% p]: [% l-1]% c% x% d% u% a% h",
      "log_lock_waits": "on",
      "log_min_duration_statement": 500,
      "log_statement": "ddl",
      "log_temp_files": 0,
      "max_connections": 136,
      "max_replication_slots": 10,
      "max_wal_senders": 10,
      "tcp_keepalives_idle": 900,
      "tcp_keepalives_interval": 100,
      "track_functions": "all",
      "wal_keep_segments": 8,
      "wal_level": "hot_standby",
      "wal_log_hints": "on"
    },
    "use_pg_rewind": true,
    "use_slots": true
  },
  "retry_timeout": 20,
  "ttl": 60
}

Unfortunately the error message "failed to update leader lock" still appears very often in the logs.
What other cause could this error message have?

Thanks

**Comment by CyberDem0n** [comment]
> What other cause could this error message have?

Providing a bit more Patroni logs could help to understand the problem.
Also I would recommend you to look at kube-apiserver logs.

**Comment by Reinhard-F** [comment]
Hi @CyberDem0n 

this message occurs in all databases of our Kubernetes cluster **at different times**:
`
2021-02-04 18:20:17,381 INFO: no action.  i am the leader with the lock
2021-02-04 18:20:27,362 INFO: Lock owner: next-database-0; I am next-database-0
2021-02-04 18:20:37,373 ERROR: Request to server https://10.240.16.1:443 failed: ReadTimeoutError("HTTPSConnectionPool(host='10.240.16.1', port=443): Read timed out. (read timeout=9.99960580188781)",)
2021-02-04 18:20:37,645 WARNING: Concurrent update of next-database
2021-02-04 18:20:38,646 ERROR: failed to update leader lock
2021-02-04 18:20:38,843 INFO: demoted self because failed to update leader lock in DCS
2021-02-04 18:20:38,853 WARNING: Loop time exceeded, rescheduling immediately.
2021-02-04 18:20:38,855 INFO: Lock owner: next-database-0; I am next-database-0
2021-02-04 18:20:38,856 INFO: closed patroni connection to the postgresql cluster
2021-02-04 18:20:38,873 WARNING: Concurrent update of next-database
2021-02-04 18:20:39,652 INFO: postmaster pid=2888
/var/run/postgresql:5432 - no response
2021-02-04 18:20:39 UTC [2888]: [1-1] 601c3af7.b48 0     LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...
2021-02-04 18:20:39 UTC [2888]: [2-1] 601c3af7.b48 0     LOG:  pg_stat_kcache.linux_hz is set to 500000
2021-02-04 18:20:39 UTC [2888]: [3-1] 601c3af7.b48 0     LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-02-04 18:20:39 UTC [2888]: [4-1] 601c3af7.b48 0     LOG:  listening on IPv6 address "::", port 5432
2021-02-04 18:20:39 UTC [2888]: [5-1] 601c3af7.b48 0     LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-02-04 18:20:39 UTC [2888]: [6-1] 601c3af7.b48 0     LOG:  redirecting log output to logging collector process
2021-02-04 18:20:39 UTC [2888]: [7-1] 601c3af7.b48 0     HINT:  Future log output will appear in directory "../pg_log".
2021-02-04 18:20:39,895 INFO: starting after demotion in progress
2021-02-04 18:20:40.461 37 LOG {ticks: 0, maint: 0, retry: 0}
/var/run/postgresql:5432 - accepting connections
/var/run/postgresql:5432 - accepting connections
2021-02-04 18:20:40,733 INFO: Lock owner: next-database-0; I am next-database-0
2021-02-04 18:20:40,733 INFO: establishing a new patroni connection to the postgres cluster
2021-02-04 18:20:40,752 WARNING: Concurrent update of next-database
2021-02-04 18:20:41,753 ERROR: failed to update leader lock
2021-02-04 18:20:41,799 INFO: not promoting because failed to update leader lock in DCS
2021-02-04 18:20:51,232 INFO: Lock owner: next-database-0; I am next-database-0
2021-02-04 18:20:51,243 WARNING: Concurrent update of next-database
2021-02-04 18:20:52,245 ERROR: failed to update leader lock
2021-02-04 18:20:52,245 INFO: not promoting because failed to update leader lock in DCS
2021-02-04 18:21:01,232 INFO: Lock owner: next-database-0; I am next-database-0
2021-02-04 18:21:01,269 INFO: promoted self to leader because i had the session lock
server promoting
2021-02-04 18:21:01,304 INFO: cleared rewind state after becoming the leader
2021-02-04 18:21:03,330 INFO: Lock owner: next-database-0; I am next-database-0
2021-02-04 18:21:03,436 INFO: no action.  i am the leader with the lock
2021-02-04 18:21:03,507 INFO: Lock owner: next-database-0; I am next-database-0
DO
2021-02-04 18:21:03,800 INFO: no action.  i am the leader with the lock
DO
DO
NOTICE:  extension "pg_auth_mon" already exists, skipping
CREATE EXTENSION
NOTICE:  version "1.0" of extension "pg_auth_mon" is already installed
ALTER EXTENSION
GRANT
NOTICE:  extension "pg_cron" already exists, skipping
CREATE EXTENSION
NOTICE:  version "1.3" of extension "pg_cron" is already installed
ALTER EXTENSION
ALTER POLICY
...
`

This message appears in all databases of our Kubernetes clusters **at the same time**:
`
2021-02-10 03:19:48,464 INFO: no action.  i am the leader with the lock
2021-02-10 03:19:48,466 WARNING: Loop time exceeded, rescheduling immediately.
2021-02-10 03:19:48,467 INFO: Lock owner: next-database-0; I am next-database-0
2021-02-10 03:19:58,479 ERROR: Request to server https://10.240.16.1:443 failed: ReadTimeoutError("HTTPSConnectionPool(host='10.240.16.1', port=443): Read timed out. (read timeout=9.999733706004918)",)
2021-02-10 03:20:03,891 ERROR: Request to server https://10.240.16.1:443 failed: ReadTimeoutError("HTTPSConnectionPool(host='10.240.16.1', port=443): Read timed out. (read timeout=4.57010193914175)",)
2021-02-10 03:20:05,519 ERROR: Request to server https://10.240.16.1:443 failed: ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
2021-02-10 03:20:16,095 INFO: no action.  i am the leader with the lock
2021-02-10 03:20:16,097 WARNING: Loop time exceeded, rescheduling immediately.
2021-02-10 03:20:16,098 INFO: Lock owner: next-database-0; I am next-database-0
2021-02-10 03:20:16.417 37 LOG {ticks: 0, maint: 0, retry: 0}
2021-02-10 03:20:26,112 ERROR: Request to server https://10.240.16.1:443 failed: ReadTimeoutError("HTTPSConnectionPool(host='10.240.16.1', port=443): Read timed out. (read timeout=9.882921746000648)",)
2021-02-10 03:20:36,610 INFO: no action.  i am the leader with the lock
2021-02-10 03:20:36,611 WARNING: Loop time exceeded, rescheduling immediately.
2021-02-10 03:20:36,613 INFO: Lock owner: next-database-0; I am next-database-0
2021-02-10 03:20:40,718 ERROR: Permission denied
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 897, in _update_leader_with_retry
    return self._patch_or_create(self.leader_path, annotations, resource_version, ips=ips, retry=_retry)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 854, in _patch_or_create
    ret = retry(func, self._namespace, body) if retry else func(self._namespace, body)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 894, in _retry
    return retry(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/utils.py", line 333, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 466, in wrapper
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 402, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 371, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 201, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 10 Feb 2021 03:20:40 GMT', 'Content-Length': '628'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"endpoints \\"next-database\\" is forbidden: User \\"system:serviceaccount:next:postgres-pod\\" cannot patch resource \\"endpoints\\" in API group \\"\\" in the namespace \\"next\\": RBAC: [clusterrole.rbac.authorization.k8s.io \\"system:basic-user\\" not found, clusterrole.rbac.authorization.k8s.io \\"system:discovery\\" not found, clusterrole.rbac.authorization.k8s.io \\"system:public-info-viewer\\" not found]","reason":"Forbidden","details":{"name":"next-database","kind":"endpoints"},"code":403}\n'

2021-02-10 03:20:40,721 ERROR: failed to update leader lock
2021-02-10 03:20:46.446 37 LOG {ticks: 0, maint: 0, retry: 0}
2021-02-10 03:20:50,849 INFO: demoted self because failed to update leader lock in DCS
2021-02-10 03:20:50,851 WARNING: Loop time exceeded, rescheduling immediately.
2021-02-10 03:20:50,852 INFO: Lock owner: next-database-0; I am next-database-0
2021-02-10 03:20:50,853 INFO: closed patroni connection to the postgresql cluster
2021-02-10 03:20:51,221 INFO: postmaster pid=27804
/var/run/postgresql:5432 - no response
2021-02-10 03:20:51 UTC [27804]: [1-1] 60235113.6c9c 0     LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...
2021-02-10 03:20:51 UTC [27804]: [2-1] 60235113.6c9c 0     LOG:  pg_stat_kcache.linux_hz is set to 1000000
2021-02-10 03:20:51 UTC [27804]: [3-1] 60235113.6c9c 0     LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-02-10 03:20:51 UTC [27804]: [4-1] 60235113.6c9c 0     LOG:  listening on IPv6 address "::", port 5432
2021-02-10 03:20:51 UTC [27804]: [5-1] 60235113.6c9c 0     LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-02-10 03:20:51 UTC [27804]: [6-1] 60235113.6c9c 0     LOG:  redirecting log output to logging collector process
2021-02-10 03:20:51 UTC [27804]: [7-1] 60235113.6c9c 0     HINT:  Future log output will appear in directory "../pg_log".
/var/run/postgresql:5432 - accepting connections
/var/run/postgresql:5432 - accepting connections
2021-02-10 03:21:00,864 ERROR: Request to server https://10.240.16.1:443 failed: ReadTimeoutError("HTTPSConnectionPool(host='10.240.16.1', port=443): Read timed out. (read timeout=9.98159867245704)",)
2021-02-10 03:21:06,207 ERROR: Request to server https://10.240.16.1:443 failed: ReadTimeoutError("HTTPSConnectionPool(host='10.240.16.1', port=443): Read timed out. (read timeout=4.632020900025964)",)
2021-02-10 03:21:06,927 ERROR: Request to server https://10.240.16.1:443 failed: ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-02-10 03:21:07,458 INFO: updated leader lock during starting after demotion
2021-02-10 03:21:07,462 WARNING: Loop time exceeded, rescheduling immediately.
2021-02-10 03:21:07,464 INFO: Lock owner: next-database-0; I am next-database-0
2021-02-10 03:21:07,464 INFO: establishing a new patroni connection to the postgres cluster
2021-02-10 03:21:16.453 37 LOG {ticks: 0, maint: 0, retry: 0}
2021-02-10 03:21:17,488 ERROR: Request to server https://10.240.16.1:443 failed: ReadTimeoutError("HTTPSConnectionPool(host='10.240.16.1', port=443): Read timed out. (read timeout=9.997781009413302)",)
2021-02-10 03:21:22,759 ERROR: Request to server https://10.240.16.1:443 failed: ReadTimeoutError("HTTPSConnectionPool(host='10.240.16.1', port=443): Read timed out. (read timeout=4.710326288826764)",)
2021-02-10 03:21:23,340 ERROR: Permission denied
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 897, in _update_leader_with_retry
    return self._patch_or_create(self.leader_path, annotations, resource_version, ips=ips, retry=_retry)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 854, in _patch_or_create
    ret = retry(func, self._namespace, body) if retry else func(self._namespace, body)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 894, in _retry
    return retry(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/utils.py", line 333, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 466, in wrapper
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 402, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 371, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 201, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 10 Feb 2021 03:21:23 GMT', 'Content-Length': '400'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"endpoints \\"next-database\\" is forbidden: User \\"system:serviceaccount:next:postgres-pod\\" cannot patch resource \\"endpoints\\" in API group \\"\\" in the namespace \\"next\\"","reason":"Forbidden","details":{"name":"next-database","kind":"endpoints"},"code":403}\n'

2021-02-10 03:21:23,340 ERROR: failed to update leader lock
2021-02-10 03:21:23,360 ERROR: Permission denied
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 481, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 1002, in touch_member
    ret = self._api.patch_namespaced_pod(self._name, self._namespace, body)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 466, in wrapper
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 402, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 371, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 201, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 10 Feb 2021 03:21:23 GMT', 'Content-Length': '389'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"next-database-0\\" is forbidden: User \\"system:serviceaccount:next:postgres-pod\\" cannot patch resource \\"pods\\" in API group \\"\\" in the namespace \\"next\\"","reason":"Forbidden","details":{"name":"next-database-0","kind":"pods"},"code":403}\n'

2021-02-10 03:21:23,361 INFO: not promoting because failed to update leader lock in DCS
`

I cannot give you any logs from the kube-apiserver, because it is a managed kubernetes cluster.

Find attached the log from 3 databases in our kubernetes cluster.
[test-mm-db.zip](https://github.com/zalando/postgres-operator/files/5965096/test-mm-db.zip)
[test-nfl-db.zip](https://github.com/zalando/postgres-operator/files/5965098/test-nfl-db.zip)
[test-nmb-db.zip](https://github.com/zalando/postgres-operator/files/5965099/test-nmb-db.zip)

Could the problem be that the API server is not responding at these times?

**Comment by CyberDem0n** [comment]
> Could the problem be that the API server is not responding at these times?

According to the number of exceptions in your logs it is very likely.

> I cannot give you any logs from the kube-apiserver, because it is a managed kubernetes cluster.

Hmm, does disallow doing `kubectl logs -n kube-system  kube-apiserver.....` ?

**Comment by Reinhard-F** [comment]
The command kubectl -n kube-system logs kube-apiserver is responding with kube-apiserver not found.
kubectl -n kube-system get pods shows no pod with kube-apiserver*.
I'am searching on our worker nodes for an apiserver log, described here: https://kubernetes.io/docs/tasks/debug-application-cluster/debug-cluster/ --> There is no log
Is a kubelet log created with 'journalctl -u kubelet --since "8 days ago"' helpfully?

Thanks

**Comment by FxKu** [comment]
Can this be closed @Reinhard-F? Looks unrelated to the operator.
