### ISSUE TITLE
Not able to modify db resource limits and requests from ui

### ISSUE THREAD

**Issue by niraj-fareye** [zalando/postgres-operator#1532]
I am trying to modify database limits and requests cpu and memory but getting some error and not getting modified values in statfulset.
operator_ui.main INFO     Changes to: acid-test-user-db by local-user/['acid'] {'spec': {'allowedSourceRanges': [], 'numberOfInstances': 1, 'enableMasterLoadBalancer': False, 'enableReplicaLoadBalancer': False, 'enableConnectionPooler': False, 'volume': {'size': '15Gi'}, 'users': {'testuser': []}, 'databases': {'testuser': 'testuser'}, 'resources': {'limits': {'cpu': '2000m', 'memory': '4096Mi'}, 'requests': {'cpu': '250m', 'memory': '512Mi'}}}}
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 934, in emit
    self.socket.send(msg)
  File "/usr/lib/python3.8/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
  File "/usr/lib/python3.8/site-packages/gevent/_socket3.py", line 55, in _dummy
    raise OSError(EBADF, 'Bad file descriptor')
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 855, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.8/site-packages/gevent/_socketcommon.py", line 628, in connect
    raise _SocketError(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 937, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.8/logging/handlers.py", line 866, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.8/site-packages/gevent/_socketcommon.py", line 628, in connect
    raise _SocketError(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/lib/python3.8/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/lib/python3.8/site-packages/gevent/pywsgi.py", line 1577, in handle
    handler.handle()
  File "/usr/lib/python3.8/site-packages/gevent/pywsgi.py", line 464, in handle
    result = self.handle_one_request()
  File "/usr/lib/python3.8/site-packages/gevent/pywsgi.py", line 694, in handle_one_request
    self.handle_one_response()
  File "/usr/lib/python3.8/site-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/usr/lib/python3.8/site-packages/gevent/pywsgi.py", line 945, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/operator_ui/main.py", line 166, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/operator_ui/main.py", line 196, in wrapper
    return f(*args, **kwargs)
  File "/operator_ui/main.py", line 558, in run
    return handler(*args, **kwargs)
  File "/operator_ui/main.py", line 588, in update_postgresql
    logger.info(f'Changes to: {cluster} by {session.get("user_name", "local-user")}/{teams} {postgresql}')  # noqa
Message: "Changes to: acid-test-user-db by local-user/['acid'] {'spec': {'allowedSourceRanges': [], 'numberOfInstances': 1, 'enableMasterLoadBalancer': False, 'enableReplicaLoadBalancer': False, 'enableConnectionPooler': False, 'volume': {'size': '15Gi'}, 'users': {'testuser': []}, 'databases': {'testuser': 'testuser'}, 'resources': {'limits': {'cpu': '2000m', 'memory': '4096Mi'}, 'requests': {'cpu': '250m', 'memory': '512Mi'}}}}

**Comment by FxKu** [comment]
Closing for #1620.
