### ISSUE TITLE
not working on k3s

### ISSUE THREAD

**Issue by viorel-anghel** [zalando/postgres-operator#1583]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** k3s single node, tested on local and DigitalOcean VMs
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

The operator is not working in K3S (certified Kubernetes distribution) single node cluster. I know this is somehow strange, why would anyone trying to run a HA solution on a single node Kubernetes cluster, but Zalando Postgres Operator is perfectly working in KIND (also single node).

How to reproduce
- on a fresh/clean VM install k3s -- https://www.k3s.io/
- setup kubeconfig: `mkdir -p .kube ; ln -s /etc/rancher/k3s/k3s.yaml .kube/config`
- install zalando: `helm install postgres-operator ./charts/postgres-operator`
- setup the minimal cluster: `kubectl create -f manifests/minimal-postgres-manifest.yaml`
- the postgresql cluster will never be created. in the end, the operator will show something like:

```
kubectl get postgresql
NAME                   TEAM   VERSION   PODS   VOLUME   CPU-REQUEST   MEMORY-REQUEST   AGE    STATUS
acid-minimal-cluster   acid   13        2      1Gi                                     104m   **SyncFailed**
```

the postgresql pods will never get the master/replica role:
```
kubectl get pods -l application=spilo -L spilo-role
NAME                     READY   STATUS    RESTARTS   AGE   SPILO-ROLE
acid-minimal-cluster-0   1/1     Running   0          27m
acid-minimal-cluster-1   1/1     Running   0          26m
```

the postgres-operator logs shows
```
kubectl logs postgres-operator-c9878f596-z9ddn
[...]
time="2021-08-16T08:55:44Z" level=error msg="failed to create cluster: pod labels error: still failing after 200 retries" cluster-name=default/acid-minimal-cluster pkg=cluster worker=0
[...]
```

the postgres pods shows
```
kubectl logs acid-minimal-cluster-0
[...]
initdb: error: could not access directory "/home/postgres/pgdata/pgroot/data": Permission denied
pg_ctl: database system initialization failed
2021-08-16 08:45:50,022 INFO: removing initialize key after failed attempt to bootstrap the cluster
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 33, in <module>
    sys.exit(load_entry_point('patroni==2.0.2', 'console_scripts', 'patroni')())
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 108, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 111, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1457, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1351, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1247, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1240, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
/run/service/patroni: finished with code=1 signal=0
```

I have read https://github.com/docker-library/postgres/issues/451 and I don't think is related, huge_pages is disabled:
```
cat /proc/sys/vm/nr_hugepages
0
```

**Comment by viorel-anghel** [comment]
the following workaround will solve the problem: enter in both postgres pods, something like `kubectl exec -ti acid-minimal-cluster-1  bash` and run `chown postgres pgdata`and `sv restart patroni`. after this:
```
kubectl get pods -l application=spilo -L spilo-role
NAME                     READY   STATUS    RESTARTS   AGE     SPILO-ROLE
acid-minimal-cluster-0   1/1     Running   0          8m58s   master
acid-minimal-cluster-1   1/1     Running   0          7m48s   replica

kubectl get postgresql
NAME                   TEAM   VERSION   PODS   VOLUME   CPU-REQUEST   MEMORY-REQUEST   AGE   STATUS
acid-minimal-cluster   acid   13        2      1Gi                                     11m   Running

**Comment by viorel-anghel** [comment]
moved to https://github.com/zalando/spilo/issues/610 - also with a solution now.
