### ISSUE TITLE
[UI] CPU and Memory Resize Not Working On Postgres Operator

### ISSUE THREAD

**Issue by KumarAshish155** [zalando/postgres-operator#1620]
- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.7.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [EKS]
- **Are you running Postgres Operator in production?** [yes ]
- **Type of issue?** [question]

I am trying to resize the resources Of The Stateful Set From UI.

Exception:-

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 936, in emit
    self.socket.send(msg)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 390, in send
    return _socket.socket.send(self._sock, data, flags)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 857, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 307, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 939, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.6/logging/handlers.py", line 868, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 307, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/lib/python3.6/site-packages/gevent/pywsgi.py", line 1482, in handle
    handler.handle()
  File "/usr/lib/python3.6/site-packages/gevent/pywsgi.py", line 454, in handle
    result = self.handle_one_request()
  File "/usr/lib/python3.6/site-packages/gevent/pywsgi.py", line 671, in handle_one_request
    self.handle_one_response()
  File "/usr/lib/python3.6/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
    self.run_application()
  File "/usr/lib/python3.6/site-packages/gevent/pywsgi.py", line 908, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/operator_ui/main.py", line 163, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/operator_ui/main.py", line 193, in wrapper
    return f(*args, **kwargs)
  File "/operator_ui/main.py", line 551, in run
    return handler(*args, **kwargs)
  File "/operator_ui/main.py", line 584, in update_postgresql
    logger.info(f'Allowing edit due to membership in superuser team {SUPERUSER_TEAM}')  # noqa
Message: 'Allowing edit due to membership in superuser team acid'

```

**Comment by KumarAshish155** [comment]
Hi Guys,

This is a critical issue we are facing. Can someone from the community help us?

**Comment by CyberDem0n** [comment]
> From UI.

What stops you from using `kubectl edit pg`?
