### ISSUE TITLE
Operator logging has to be improved and some information if the cluster is not in desired state required 

### ISSUE THREAD

**Issue by cspwizard** [zalando/postgres-operator#1674]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** 
registry.opensource.zalan.do/acid/postgres-operator:v1.7.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** 
k8s set up with rke (Rancher)
- **Are you running Postgres Operator in production?**
not yet
- **Type of issue?** [Bug report, question, feature request, etc.]
Improvement

There is an issue with operator logs and probably error handling. Operator fails and restarts not applying configuration, in the restarted pod there is nothing about the pending update or problem that there was.  I've met this situation couple times already and it's very annoying. 

Operator fails with the next log:

```

time="2021-11-05T09:17:05Z" level=error msg="could not get reference for Postgresql CR 3529-pg-cluster/team-postgresql: no kind is registered for the type v1.Postgresql in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:72\"" pkg=controller
E1105 09:17:05.718258       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 97 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1d1cba0, 0x30c2200)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1d1cba0, 0x30c2200)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/client-go/tools/record.(*recorderImpl).makeEvent(0xc000188e00, 0x0, 0x0, 0x1fdf76d, 0x7, 0x1fdea68, 0x6, 0xc00071ea80, 0x60, 0xc000a64270)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:365 +0x51
k8s.io/client-go/tools/record.(*recorderImpl).generateEvent(0xc000188e00, 0x2340e18, 0x0, 0x0, 0x1fdf76d, 0x7, 0x1fdea68, 0x6, 0xc00071ea80, 0x60)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:338 +0x359
k8s.io/client-go/tools/record.(*recorderImpl).Event(...)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:352
k8s.io/client-go/tools/record.(*recorderImpl).Eventf(0xc000188e00, 0x2340e18, 0x0, 0x1fdf76d, 0x7, 0x1fdea68, 0x6, 0x1fdca02, 0x2, 0xc000bd1bd0, ...)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:356 +0xd6
github.com/zalando/postgres-operator/pkg/controller.(*Controller).queueClusterEvent(0xc00025bc00, 0xc00165a000, 0xc000071000, 0x1fdea56, 0x6)
	/workspace/pkg/controller/postgresql.go:449 +0x8c7
github.com/zalando/postgres-operator/pkg/controller.(*Controller).postgresqlUpdate(0xc00025bc00, 0x1f9dc60, 0xc00165a000, 0x1f9dc60, 0xc000071000)
	/workspace/pkg/controller/postgresql.go:522 +0x145
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/workspace/vendor/k8s.io/client-go/tools/cache/controller.go:238
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/vendor/k8s.io/client-go/tools/cache/shared_informer.go:775 +0x1c5
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000893f60)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a09f60, 0x2331d40, 0xc00057e000, 0x1ccb601, 0xc00057c000)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000893f60, 0x3b9aca00, 0x0, 0x1, 0xc00057c000)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0004d7880)
	/workspace/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0002bebc0, 0xc00057a000)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x19c3511]
goroutine 97 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1d1cba0, 0x30c2200)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/client-go/tools/record.(*recorderImpl).makeEvent(0xc000188e00, 0x0, 0x0, 0x1fdf76d, 0x7, 0x1fdea68, 0x6, 0xc00071ea80, 0x60, 0xc000a64270)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:365 +0x51
k8s.io/client-go/tools/record.(*recorderImpl).generateEvent(0xc000188e00, 0x2340e18, 0x0, 0x0, 0x1fdf76d, 0x7, 0x1fdea68, 0x6, 0xc00071ea80, 0x60)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:338 +0x359
k8s.io/client-go/tools/record.(*recorderImpl).Event(...)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:352
k8s.io/client-go/tools/record.(*recorderImpl).Eventf(0xc000188e00, 0x2340e18, 0x0, 0x1fdf76d, 0x7, 0x1fdea68, 0x6, 0x1fdca02, 0x2, 0xc000bd1bd0, ...)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:356 +0xd6
github.com/zalando/postgres-operator/pkg/controller.(*Controller).queueClusterEvent(0xc00025bc00, 0xc00165a000, 0xc000071000, 0x1fdea56, 0x6)
	/workspace/pkg/controller/postgresql.go:449 +0x8c7
github.com/zalando/postgres-operator/pkg/controller.(*Controller).postgresqlUpdate(0xc00025bc00, 0x1f9dc60, 0xc00165a000, 0x1f9dc60, 0xc000071000)
	/workspace/pkg/controller/postgresql.go:522 +0x145
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/workspace/vendor/k8s.io/client-go/tools/cache/controller.go:238
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/vendor/k8s.io/client-go/tools/cache/shared_informer.go:775 +0x1c5
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000893f60)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a09f60, 0x2331d40, 0xc00057e000, 0x1ccb601, 0xc00057c000)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000893f60, 0x3b9aca00, 0x0, 0x1, 0xc00057c000)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0004d7880)
	/workspace/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0002bebc0, 0xc00057a000)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65

```

It's absolutely impossible to understand what went wrong. In my case I've met this couple times, when specified cluster name without team prefix and when I used numeric value as an env parameter for the sidecar container. Both times it gets me plenty of time to find what caused the error. 

If there would be at least clear error in the log it could save a lot of time and effort. On another hand if there would be a validation 
Also this kind of behavior leads to a bigger problem: you can't understand if the cluster is in the desired state (specified by the yml) or not.

**Comment by FxKu** [comment]
duplicate to https://github.com/zalando/postgres-operator/issues/1413. Can you close either one of the issues?
