### ISSUE TITLE
panic: configmaps "postgres-operator" not found

### ISSUE THREAD

**Issue by microyahoo** [zalando/postgres-operator#1806]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.7.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [K8s]
- **Are you running Postgres Operator in production?** [no]
- **Type of issue?** [Bug report.]

I have followed the guide of [Configuration parameters](https://github.com/zalando/postgres-operator/blob/master/docs/reference/operator_parameters.md) to setup postgres cluster as follows:
```
kubectl create -f manifests/operatorconfiguration.crd.yaml # registers the CRD
kubectl create -f manifests/postgresql-operator-default-configuration.yaml

kubectl create -f manifests/operator-service-account-rbac.yaml
kubectl create -f manifests/postgres-operator.yaml # set the env var as mentioned above
```
postgres-operator pod failed with CrashLoopBackOff as configmaps "postgres-operator" not found. As the document mentioned,  the ConfigMap-based configuration will be deprecated and subsequently removed in future releases.
```
🍺 /root/go/src/github.com/zalando/postgres-operator ☞ git:(master) ✗ kubectl get all -o wide -n pgo
NAME                                     READY   STATUS             RESTARTS      AGE   IP            NODE                       NOMINATED NODE   READINESS GATES
pod/postgres-operator-569b58b8c6-vjlf6   0/1     CrashLoopBackOff   8 (58s ago)   17m   10.244.0.74   glusterfs-1.deeproute.ai   <none>           <none>

NAME                                READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS          IMAGES                                                       SELECTOR
deployment.apps/postgres-operator   0/1     1            0           17m   postgres-operator   registry.opensource.zalan.do/acid/postgres-operator:v1.7.1   name=postgres-operator

NAME                                           DESIRED   CURRENT   READY   AGE   CONTAINERS          IMAGES                                                       SELECTOR
replicaset.apps/postgres-operator-569b58b8c6   1         1         0       17m   postgres-operator   registry.opensource.zalan.do/acid/postgres-operator:v1.7.1   name=postgres-operator,pod-template-hash=569b58b8c6

NAME                                                                            IMAGE                                               CLUSTER-LABEL   SERVICE-ACCOUNT   MIN-INSTANCES   AGE
operatorconfiguration.acid.zalan.do/postgresql-operator-default-configuration   registry.opensource.zalan.do/acid/spilo-14:2.1-p3   cluster-name    postgres-pod      -1              27m
```
```
➜ /root/go/src/github.com/zalando/postgres-operator ☞ git:(master) ✗ kubectl logs -n pgo deployment.apps/postgres-operator
time="2022-03-03T09:10:30Z" level=info msg="Spilo operator v1.7.1\n"
time="2022-03-03T09:10:30Z" level=info msg="Fully qualified configmap name: pgo/postgres-operator"
panic: configmaps "postgres-operator" not found

goroutine 1 [running]:
github.com/zalando/postgres-operator/pkg/controller.(*Controller).initOperatorConfig(0xc0001ec000)
	/workspace/pkg/controller/controller.go:142 +0x62d
github.com/zalando/postgres-operator/pkg/controller.(*Controller).initController(0xc0001ec000)
	/workspace/pkg/controller/controller.go:319 +0x88e
github.com/zalando/postgres-operator/pkg/controller.(*Controller).Run(0xc0001ec000, 0xc000120ea0, 0xc00011e1f0)
	/workspace/pkg/controller/controller.go:434 +0x2f
main.main()
	/workspace/cmd/main.go:87 +0x2b6
```

**Comment by microyahoo** [comment]
It is my fault, I forget to update the `env` in postgres-operator.yaml
