### ISSUE TITLE
Missing subscriber channel for pooler pods

### ISSUE THREAD

**Issue by FxKu** [zalando/postgres-operator#1867]
How to replicate:
1. Create cluster with 2 spilo and pooler pods.
2. Trigger a switchover by changing the manifest

```
panic: send on closed channel

goroutine 366 [running]:
github.com/zalando/postgres-operator/pkg/cluster.(*Cluster).processPodEvent(0xc00064a000, {0x1bdc360, 0xc000a0ef00})
	/workspace/pkg/cluster/cluster.go:1037 +0x205
k8s.io/client-go/tools/cache.(*FIFO).Pop(0xc000e5b8c0, 0xc000a2ff90)
	/workspace/vendor/k8s.io/client-go/tools/cache/fifo.go:300 +0x1fc
github.com/zalando/postgres-operator/pkg/cluster.(*Cluster).processPodEventQueue(0xc00064a000, 0x0)
	/workspace/pkg/cluster/cluster.go:1054 +0x65
created by github.com/zalando/postgres-operator/pkg/cluster.(*Cluster).Run
	/workspace/pkg/cluster/cluster.go:1045 +0x77
```

The operator pod comes back immediately and finishes the rolling update as expected (since it finds the corresponding annotations on the pods to be rotated). It seems that subscribers are missing if there is more than one pooler pod.

**Comment by Samusername** [comment]
I think, we saw this same problem now also.

<details>
  <summary>Click to expand!</summary>
time="2022-05-02T11:03:17Z" level=debug msg="subscribing to pod \"nom-backend/mydb-cluster-0\"" cluster-name=nom-backend/mydb-cluster pkg=cluster
panic: send on closed channel
 
goroutine 72 [running]:
github.com/zalando/postgres-operator/pkg/cluster.(*Cluster).processPodEvent(0xc00002f000, {0x1bdc540, 0xc000aa5180})
    /home/jenkins/workspace/NM/Neo/service/mydb-operator/tmp-src/postgres-operator-1.8.0/pkg/cluster/cluster.go:1037 +0x205
k8s.io/client-go/tools/cache.(*FIFO).Pop(0xc00071c510, 0xc0004fb790)
    /home/jenkins/workspace/NM/Neo/service/mydb-operator/tmp-src/postgres-operator-1.8.0/vendor/k8s.io/client-go/tools/cache/fifo.go:300 +0x1fc
github.com/zalando/postgres-operator/pkg/cluster.(*Cluster).processPodEventQueue(0xc00002f000, 0x0)
    /home/jenkins/workspace/NM/Neo/service/mydb-operator/tmp-src/postgres-operator-1.8.0/pkg/cluster/cluster.go:1054 +0x65
created by github.com/zalando/postgres-operator/pkg/cluster.(*Cluster).Run
    /home/jenkins/workspace/NM/Neo/service/mydb-operator/tmp-src/postgres-operator-1.8.0/pkg/cluster/cluster.go:1045 +0x77

</details>

Wondering, did this occur also before version v1.8.0 of postgres-operator?
