### ISSUE TITLE
Regular problems with the cluster. How to decide?

### ISSUE THREAD

**Issue by maxinfosoft** [zalando/postgres-operator#1880]
Regular problems with the cluster. How to decide?

After a certain time, after filling the disk (30GB) with wal-files, the database becomes inaccessible through pooler.
Each time after such a failure, I am forced to create a new cluster through the Operator UI and upload a dump of the old database.
Below I have placed the logs.

How to avoid such a problem?
How to solve such a problem when it arises?

My cluster configuration:
AWS EKS 1.22
registry.opensource.zalan.do/acid/postgres-operator-ui:v1.7.1

-----------------------------------------------------------------------

Logs from acid-myservice-postgresql12-cluster-1 :

/var/run/postgresql:5432 - rejecting connections
2022-05-05 09:37:43,234 INFO: Lock owner: None; I am acid-myservice-postgresql12-cluster-1
2022-05-05 09:37:43,235 INFO: Still starting up as a standby.
2022-05-05 09:37:43,236 INFO: establishing a new patroni connection to the postgres cluster
2022-05-05 09:37:43,938 INFO: establishing a new patroni connection to the postgres cluster
2022-05-05 09:37:43,940 WARNING: Retry got exception: 'connection problems'
2022-05-05 09:37:43,940 INFO: Error communicating with PostgreSQL. Will try again later

-----------------------------------------------------------------------

Logs from acid-myservice-postgresql12-cluster-0 :

2022-05-05 09:40:07,119 INFO: establishing a new patroni connection to the postgres cluster
2022-05-05 09:40:07,772 INFO: establishing a new patroni connection to the postgres cluster
2022-05-05 09:40:07,775 WARNING: Retry got exception: 'connection problems'
2022-05-05 09:40:07,775 INFO: Error communicating with PostgreSQL. Will try again later
/var/run/postgresql:5432 - rejecting connections
2022-05-05 09:40:17,118 INFO: Lock owner: None; I am acid-myservice-postgresql12-cluster-0
2022-05-05 09:40:17,119 INFO: Still starting up as a standby.
2022-05-05 09:40:17,120 INFO: establishing a new patroni connection to the postgres cluster
/var/run/postgresql:5432 - rejecting connections
2022-05-05 09:40:27,127 INFO: Lock owner: None; I am acid-myservice-postgresql12-cluster-0
2022-05-05 09:40:27,128 INFO: Still starting up as a standby.
2022-05-05 09:40:27,129 INFO: establishing a new patroni connection to the postgres cluster
/var/run/postgresql:5432 - rejecting connections
2022-05-05 09:40:37,119 INFO: Lock owner: None; I am acid-myservice-postgresql12-cluster-0
2022-05-05 09:40:37,120 INFO: Still starting up as a standby.

-----------------------------------------------------------------------

Logs from acid-myservice-postgresql12-cluster-pooler-254fbb49cd-crkwq : 

2022-05-05 09:38:45.617 UTC [1] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
2022-05-05 09:38:45.668 UTC [1] WARNING C-0x55d95972db90: myservice/(nouser)@127.0.0.6:38253 pooler error: pgbouncer cannot connect to server
2022-05-05 09:38:46.679 UTC [1] WARNING C-0x55d95972db90: myservice/(nouser)@127.0.0.6:45441 pooler error: pgbouncer cannot connect to server
2022-05-05 09:38:46.736 UTC [1] WARNING C-0x55d95972dff0: myservice/(nouser)@127.0.0.6:58229 pooler error: pgbouncer cannot connect to server
2022-05-05 09:38:48.875 UTC [1] WARNING C-0x55d95972dff0: myservice/(nouser)@127.0.0.6:43061 pooler error: pgbouncer cannot connect to server
2022-05-05 09:38:54.165 UTC [1] WARNING C-0x55d95972dff0: myservice/(nouser)@127.0.0.6:41507 pooler error: pgbouncer cannot connect to server
2022-05-05 09:38:54.557 UTC [1] WARNING C-0x55d95972dff0: myservice/(nouser)@127.0.0.6:40537 pooler error: pgbouncer cannot connect to server
2022-05-05 09:38:56.586 UTC [1] WARNING C-0x55d95972dff0: myservice/(nouser)@127.0.0.6:60305 pooler error: pgbouncer cannot connect to server
2022-05-05 09:38:56.827 UTC [1] WARNING C-0x55d95972dff0: myservice/(nouser)@127.0.0.6:43781 pooler error: pgbouncer cannot connect to server
2022-05-05 09:38:59.087 UTC [1] WARNING C-0x55d95972dff0: myservice/(nouser)@127.0.0.6:56001 pooler error: pgbouncer cannot connect to server
2022-05-05 09:39:00.506 UTC [1] WARNING C-0x55d95972dff0: myservice/(nouser)@127.0.0.6:34071 pooler error: pgbouncer cannot connect to server

Error message from DBeaver, when i try to connect via pooler :
FATAL: pgbouncer cannot connect to server

-----------------------------------------------------------------------

Logs from PostgreSQL Operator UI :

Workers 0 Logs
2022-05-05T09:39:54.170859498Z	default/acid-myservice-postgresql12-cluster	could not sync cluster: could not sync roles: could not init db connection: could not init db connection: still failing after 8 retries

**Comment by CyberDem0n** [comment]
> After a certain time, after filling the disk (30GB) with wal-files, the database becomes inaccessible through pooler.

> How to avoid such a problem?

Monitor a free disk space?

> How to solve such a problem when it arises?

Extend volume.

**Comment by maxinfosoft** [comment]
"acid-myservice-postgresql12-cluster-1" has this error:
PermissionError: [Errno 13] Permission denied: '/var/run/secrets/kubernetes.io/serviceaccount/token'

Why?

Please provide a link to the instruction on how to connect to db directly without pooler/patroni to all replicas. Thank you.

Part of the log "acid-myservice-postgresql12-cluster-1" :

Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 33, in <module>
    sys.exit(load_entry_point('patroni==1.6.5', 'console_scripts', 'patroni')())
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 235, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 197, in patroni_main
    patroni = Patroni(conf)
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 32, in __init__
    self.dcs = get_dcs(self.config)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/__init__.py", line 92, in get_dcs
    return item(config[name])
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 453, in __init__
    k8s_config.load_incluster_config()
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 69, in load_incluster_config
    with open(SERVICE_TOKEN_FILENAME) as f:
PermissionError: [Errno 13] Permission denied: '/var/run/secrets/kubernetes.io/serviceaccount/token'
/run/service/patroni: finished with code=1 signal=0
/run/service/patroni: exceeded maximum number of restarts 5
stopping /run/service/patroni
timeout: finish: .: (pid 114) 8s, want down

**Comment by maxinfosoft** [comment]
I completely removed the old operator and all entities from my kubernetes-cluster.
After that, I deployed the most recent version of operator to date via helm:
registry.opensource.zalan.do/acid/spilo-14:2.1-p5
registry.opensource.zalan.do/acid/postgres-operator:v1.8.0

When adding a new cluster through operator ui, I always get an error for acid-smartpay-postgres-0:
Readiness probe failed: HTTP probe failed with statuscode: 500
