### ISSUE TITLE
standby cluster from s3 error

### ISSUE THREAD

**Issue by meimeitou** [zalando/postgres-operator#2013]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** 
   registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? 
   Kubernetes
- **Are you running Postgres Operator in production?** 
[no]
- **Type of issue?** 
[Bug report/question]

error start standby cluster:

```
2022-08-26 03:48:58,245 WARNING: Kubernetes RBAC doesn't allow GET access to the 'kubernetes' endpoint in the 'default' namespace. Disabling 'bypass_api_service'.
2022-08-26 03:48:58,289 INFO: No PostgreSQL configuration items changed, nothing to reload.
2022-08-26 03:48:58,296 INFO: Lock owner: None; I am dns-fake-0
2022-08-26 03:48:58,461 INFO: trying to bootstrap a new standby leader
Can not find any backups
2022-08-26 03:49:04,813 ERROR: Error creating replica using method bootstrap_standby_with_wale: envdir "/run/etc/wal-e.d/env-standby" bash /scripts/wale_restore.sh exited with code=1
2022-08-26 03:49:04,814 ERROR: failed to bootstrap clone from remote master None
2022-08-26 03:49:04,815 INFO: Removing data directory: /home/postgres/pgdata/pgroot/data
2022-08-26 03:49:08,796 INFO: removing initialize key after failed attempt to bootstrap the cluster
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 143, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 135, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 105, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 108, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1514, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1388, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1280, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1273, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
/etc/runit/runsvdir/default/patroni: finished with code=1 signal=0
/etc/runit/runsvdir/default/patroni: sleeping 30 seconds
```

standby cluster config:

```yaml
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: fake
  namespace: develop
spec:
  teamId: "xx"
  numberOfInstances: 1
  postgresql:
    version: "14"
  standby:
    s3_wal_path: "s3://fake-wal/spilo/dns-fake/1cd94fa0-89ce-4438-9755-8529e2dbe2b6/wal/14/"
  volume:
    size: 2Gi
    storageClass: rook-ceph-block-ext
```

**Comment by meimeitou** [comment]
> 

yes, i am running with Ceph RWG. 
And where should I add these environment variables? in Operator `Configmap`? or just manually modify `Statefulset` resource?

**Comment by meimeitou** [comment]
> I assume you're not running in AWS? Then, for cloning to work, you'll also have to set
> 
> * `STANDBY_AWS_REGION`
> * `STANDBY_AWS_ENDPOINT`
> * `STANDBY_WAL_S3_BUCKET`
> * `STANDBY_AWS_ACCESS_KEY_ID`
> * `STANDBY_AWS_SECRET_ACCESS_KEY`
> 
> . Then it should work. And for cloning, the same game, just prefixed with `CLONE_` instead of `STANDBY_`. At least that's what it took to get it working for us.

I've added environment variables.
But there are other problems：

```shell
2022-08-29 01:29:05,421 WARNING: Kubernetes RBAC doesn't allow GET access to the 'kubernetes' endpoint in the 'default' namespace. Disabling 'bypass_api_service'.
2022-08-29 01:29:05,471 INFO: No PostgreSQL configuration items changed, nothing to reload.
2022-08-29 01:29:05,478 INFO: Lock owner: None; I am dns-fake-0
2022-08-29 01:29:05,621 INFO: trying to bootstrap a new standby leader
INFO: 2022/08/29 01:29:05.857391 Selecting the latest backup...
INFO: 2022/08/29 01:29:05.909714 LATEST backup is: 'base_000000010000000000000011_00000040'
2022-08-29 01:29:15,978 INFO: Lock owner: None; I am dns-fake-0
2022-08-29 01:29:15,978 INFO: not healthy enough for leader race
2022-08-29 01:29:16,042 INFO: bootstrap_standby_leader in progress
2022-08-29 01:29:25,978 INFO: Lock owner: None; I am dns-fake-0
2022-08-29 01:29:25,978 INFO: not healthy enough for leader race
...
```

It seems to be here？

https://github.com/zalando/patroni/blob/cea1fa869baafc077d17dd5eb1b60350d09d0592/patroni/ha.py#L1246

**Comment by jun-fcss** [comment]
I encountered the same issue, but I resolved it by directly defining the environment variables in the cluster's YML file.

For some reason, custom configmaps and secrets defined in Configmap as below,  work well when cloned, but I suspect they did not function in standby.

pod_environment_configmap: XXX 
additional_secret_mount":  XXX

I will share the cluster definition file when it's successful.

```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: fcs-pg-cluster01-standby1
spec:
  env:
  - name: ALLOW_NOSSL
    value: "true"
  - name: STANDBY_USE_WALG_BACKUP
    value: "true"
  - name: STANDBY_USE_WALG_RESTORE
    value: "true"
  - name: STANDBY_WITH_WALE
    value: "true"
  - name: STANDBY_AWS_ACCESS_KEY_ID
    value: "******"
  - name: STANDBY_AWS_SECRET_ACCESS_KEY
    value: "******"
  - name: STANDBY_AWS_REGION
    value: "ap-northeast-1"
  - name: STANDBY_AWS_ENDPOINT
    value: "https://s3.ap-northeast-1.amazonaws.com"
  - name: STANDBY_WAL_S3_BUCKET
    value: "pgo-physical-backup"

  standby:
    s3_wal_path: "s3://pgo-physical-backup/spilo/fcs-pg-cluster01/wal/14/"

  teamId: "acid"

  numberOfInstances: 1

  allowedSourceRanges:
    - 10.0.0.0/8
    - 192.168.0.0/16

  enableMasterLoadBalancer: true

  postgresql:
    version: '14'

  volume:
    size: 10Gi
```

**Comment by NIK2727** [comment]
@jun-fcss  did you get it working facing similar issue ?

**Comment by ruchiverma-12** [comment]
Hi,

I am also facing the similar issue. I am also trying to restore the backup from AWS S3 bucket in a Standby cluster but it is causing issue. I am getting below errors in logs.

------LOGS-----

2025-01-24 10:21:25,462 INFO: Lock owner: acid-test11-cluster-v14-0; I am acid-test11-cluster-v14-1
2025-01-24 10:21:25,535 INFO: bootstrap from leader 'acid-test11-cluster-v14-0' in progress
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-fetch".
        STRUCTURED: time=2025-01-24T10:21:28.077679-00 pid=93
wal_e.blobstore.s3.s3_util WARNING  MSG: WALE_S3_ENDPOINT defined, ignoring AWS_REGION
        HINT: AWS_REGION is only intended for use with AWS S3, and not interface-compatible use cases supported by WALE_S3_ENDPOINT
        STRUCTURED: time=2025-01-24T10:21:28.099649-00 pid=93
wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000000.tar.lzo.
        HINT: The absolute S3 key is spilo/dev/wal/13/basebackups_005/base_000000F50000013E00000064_00000040/tar_partitions/part_00000000.tar.lzo.
        STRUCTURED: time=2025-01-24T10:21:28.340343-00 pid=93
2025-01-24 10:21:35,458 INFO: Lock owner: acid-test11-cluster-v14-0; I am acid-test11-cluster-v14-1
2025-01-24 10:21:35,458 INFO: bootstrap from leader 'acid-test11-cluster-v14-0' in progress
2025-01-24 10:21:40,436 INFO: replica has been created using bootstrap_standby_with_wale
2025-01-24 10:21:40,438 INFO: bootstrapped from leader 'acid-test11-cluster-v14-0'
2025-01-24 10:21:40 UTC [140]: [1-1] 679369b4.8c 0     LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...
2025-01-24 10:21:40 UTC [140]: [2-1] 679369b4.8c 0     LOG:  pg_stat_kcache.linux_hz is set to 500000
2025-01-24 10:21:40,804 INFO: postmaster pid=140
/var/run/postgresql:5432 - no response
2025-01-24 10:21:40 UTC [140]: [3-1] 679369b4.8c 0     LOG:  redirecting log output to logging collector process
2025-01-24 10:21:40 UTC [140]: [4-1] 679369b4.8c 0     HINT:  Future log output will appear in directory "../pg_log".
/var/run/postgresql:5432 - rejecting connections
/var/run/postgresql:5432 - rejecting connections
/var/run/postgresql:5432 - rejecting connections
/var/run/postgresql:5432 - rejecting connections
/var/run/postgresql:5432 - rejecting connections



I am also sharing postgresql manifest file.

----

apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-test11-cluster-v14
  namespace: postgres-dev-v14
spec:
  databases:
    campaigns: ldb
    leads: ldb
  teamId: "acid-test11"
  users:
    campaigns_user: []
    ldb:
      - superuser
      - createdb
    leads_user: []
  volume:
    size: 8Gi
  numberOfInstances: 3
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"
  postgresql:
    version: "13"
    parameters:
      wal_level: hot_standby
      max_wal_senders: "10"
      max_connections: "300"
      max_replication_slots: "5"
      hot_standby: "on"
      restore_command: envdir "/run/etc/wal-e.d/env-standby" /scripts/restore_command.sh "%f" "%p" 
  standby:
    s3_wal_path: "s3://xxx/spilo/growth-db-cluster/dev/wal/13"
  env:
    - name : USE_WALG_RESTORE
      value: "false"
    - name: USE_WALE_RESTORE
      value: "true"
    - name: AWS_REGION
      value: "eu-west-1"
    - name: AWS_ACCESS_KEY_ID
      value: xxxxxxx
    - name: AWS_SECRET_ACCESS_KEY
      value: xxxxxxx
    - name: AWS_ENDPOINT
      value: "https+path://HOST"
    - name: STANDBY_USE_WALG_RESTORE
      value: "false"
    - name: STANDBY_USE_WALE_RESTORE
      value: "true"
    - name: STANDBY_AWS_ACCESS_KEY_ID
      value: xxxxxxx
    - name: STANDBY_AWS_SECRET_ACCESS_KEY
      value: xxxxxxx
    - name: STANDBY_AWS_ENDPOINT
      value: "https+path://HOST
    - name: STANDBY_AWS_REGION
      value: "eu-west-1"

Any help is much appreciated!
