### ISSUE TITLE
Replica's failing after a while

### ISSUE THREAD

**Issue by jonathon2nd** [zalando/postgres-operator#2106]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s, v1.24.4+rke2r1
- **Are you running Postgres Operator in production?** yes - soft launch
- **Type of issue?** Bug report

Hello,

We have experienced two times on one of our clusters an issue with one of the replicas. The first time I thought it might have been a fluke, but it happened again today.

![image](https://user-images.githubusercontent.com/52681917/201376237-51997ede-8b26-4b79-a074-0aa76d5abe0e.png)
One of the replica's goes offline, with the pod throwing `Readiness probe failed: HTTP probe failed with statuscode: 503`
![image](https://user-images.githubusercontent.com/52681917/201378002-bdfd2df6-96aa-42e8-b9ab-febdc979a515.png)

Log from this morning
[acid-new-polling-1_postgres.log](https://github.com/zalando/postgres-operator/files/9991427/acid-new-polling-1_postgres.log)

And the log I saved from the last time it happened
[acid-new-polling-0_postgres.log](https://github.com/zalando/postgres-operator/files/9991429/acid-new-polling-0_postgres.log)

Lines of importance?
```
2022-11-11 15:43:27,378 INFO: Lock owner: acid-new-polling-2; I am acid-new-polling-1
2022-11-11 15:43:27,433 INFO: Local timeline=None lsn=None
2022-11-11 15:43:27,433 INFO: Lock owner: acid-new-polling-2; I am acid-new-polling-1
2022-11-11 15:43:27,436 INFO: starting as a secondary
2022-11-11 15:43:27,437 ERROR: Exception during execution of long running task restarting after failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 882, in follow
    self.config.write_recovery_conf(recovery_params)
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/config.py", line 786, in write_recovery_conf
    open(self._standby_signal, 'w').close()
OSError: [Errno 30] Read-only file system: '/home/postgres/pgdata/pgroot/data/standby.signal'
2022-11-11 15:43:27,440 WARNING: Postgresql is not running.
...
2022-11-11 15:43:27,477 INFO: doing crash recovery in a single user mode
2022-11-11 15:43:27,478 ERROR: Unable to remove /home/postgres/pgdata/pgroot/data/pg_wal/archive_status/00000005000000110000005E.00000028.backup.done
...
OSError: [Errno 30] Read-only file system: '/home/postgres/pgdata/pgroot/data/pg_wal/archive_status/00000005000000110000005A.done'
2022-11-11 15:43:27,512 ERROR: Crash recovery finished with code=1
2022-11-11 15:43:27,512 INFO:  stdout=
2022-11-11 15:43:27,512 INFO:  stderr=2022-11-11 15:43:27 UTC [300466]: [1-1] 636e6d9f.495b2 0     FATAL:  could not remove old lock file "postmaster.pid": Read-only file system
2022-11-11 15:43:27 UTC [300466]: [2-1] 636e6d9f.495b2 0     HINT:  The file seems accidentally left over, but it could not be removed. Please remove the file by hand and try again.
```

Yaml for cluster
```
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: acid
  name: acid-new-polling
  namespace: polling
spec:
  allowedSourceRanges:
  - 10.0.0.0/8
  databases:
    polling: polling

  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  enableConnectionPooler: true # enable/disable connection pooler deployment
  enableReplicaConnectionPooler: false # set to enable connectionPooler for replica service

  enableLogicalBackup: true
  logicalBackupSchedule: 5 1 */3 * *
  numberOfInstances: 3
  postgresql:
    version: "14"
    parameters:  # Expert section
      shared_buffers: "32MB"
      max_connections: "100"
      log_statement: "all"
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: acid
  users:
    polling: []
  volume:
    size: 30Gi

  patroni:
    synchronous_mode: true

# overwrite custom properties for connection pooler deployments
  connectionPooler:
    numberOfInstances: 2
#    mode: "transaction"
#    schema: "pooler"
#    user: "pooler"
#    resources:
#      requests:
#        cpu: 300m
#        memory: 100Mi
    limits:
      cpu: "1"
      memory: 500Mi
```

Postgres operator log looks fine? Adding end of it.
```

{"cluster-name":"polling/acid-new-polling","level":"info","msg":"SYNC event has been queued","pkg":"controller","time":"2022-11-11T15:44:59Z","worker":0}
{"cluster-name":"tc-postgres/acid-transcoding","level":"info","msg":"SYNC event has been queued","pkg":"controller","time":"2022-11-11T15:44:59Z","worker":1}
{"level":"info","msg":"there are 2 clusters running","pkg":"controller","time":"2022-11-11T15:44:59Z"}
{"cluster-name":"tc-postgres/acid-transcoding","level":"info","msg":"syncing of the cluster started","pkg":"controller","time":"2022-11-11T15:44:59Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"team API is disabled","pkg":"cluster","time":"2022-11-11T15:44:59Z","worker":1}
{"cluster-name":"polling/acid-new-polling","level":"info","msg":"syncing of the cluster started","pkg":"controller","time":"2022-11-11T15:44:59Z","worker":0}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"team API is disabled","pkg":"cluster","time":"2022-11-11T15:44:59Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"info","msg":"syncing secrets","pkg":"cluster","time":"2022-11-11T15:44:59Z","worker":1}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"team API is disabled","pkg":"cluster","time":"2022-11-11T15:44:59Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"team API is disabled","pkg":"cluster","time":"2022-11-11T15:44:59Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"info","msg":"syncing secrets","pkg":"cluster","time":"2022-11-11T15:44:59Z","worker":0}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"syncing master service","pkg":"cluster","time":"2022-11-11T15:45:01Z","worker":1}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"syncing master service","pkg":"cluster","time":"2022-11-11T15:45:01Z","worker":0}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"syncing replica service","pkg":"cluster","time":"2022-11-11T15:45:01Z","worker":1}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"syncing replica service","pkg":"cluster","time":"2022-11-11T15:45:02Z","worker":0}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"syncing volumes using \"pvc\" storage resize mode","pkg":"cluster","time":"2022-11-11T15:45:02Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"info","msg":"volume claims do not require changes","pkg":"cluster","time":"2022-11-11T15:45:03Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"syncing statefulsets","pkg":"cluster","time":"2022-11-11T15:45:03Z","worker":1}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"syncing volumes using \"pvc\" storage resize mode","pkg":"cluster","time":"2022-11-11T15:45:03Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"info","msg":"volume claims do not require changes","pkg":"cluster","time":"2022-11-11T15:45:03Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"syncing statefulsets","pkg":"cluster","time":"2022-11-11T15:45:03Z","worker":0}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"making GET http request: http://10.42.13.25:8008/config","pkg":"cluster","time":"2022-11-11T15:45:04Z","worker":1}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"making GET http request: http://10.42.13.3:8008/config","pkg":"cluster","time":"2022-11-11T15:45:04Z","worker":0}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"making GET http request: http://10.42.52.195:8008/patroni","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"making GET http request: http://10.42.175.36:8008/patroni","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"making GET http request: http://10.42.13.25:8008/patroni","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"syncing pod disruption budgets","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
W1111 15:45:16.238051 1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"syncing logical backup job","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
W1111 15:45:16.247194 1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"Generating logical backup pod template","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"Generated logical backup env vars","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"[{SCOPE acid-transcoding nil} {CLUSTER_NAME_LABEL cluster-name nil} {POD_NAMESPACE \u0026EnvVarSource{FieldRef:\u0026ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {LOGICAL_BACKUP_PROVIDER s3 nil} {LOGICAL_BACKUP_S3_BUCKET postres-operator-k8s nil} {LOGICAL_BACKUP_S3_REGION us-east-1 nil} {LOGICAL_BACKUP_S3_ENDPOINT https://s3.wasabisys.com nil} {LOGICAL_BACKUP_S3_SSE AES256 nil} {LOGICAL_BACKUP_S3_RETENTION_TIME 90 days nil} {LOGICAL_BACKUP_S3_BUCKET_SCOPE_SUFFIX /8ebe25fe-d2f5-4d33-a89e-0d15955e3912 nil} {LOGICAL_BACKUP_GOOGLE_APPLICATION_CREDENTIALS nil} {PG_VERSION 14 nil} {PGPORT 5432 nil} {PGUSER postgres nil} {PGDATABASE postgres nil} {PGSSLMODE require nil} {PGPASSWORD \u0026EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:\u0026SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:postgres.acid-transcoding.credentials.postgresql.acid.zalan.do,},Key:password,Optional:nil,},}} {AWS_ACCESS_KEY_ID B5UEICVGITZHO6ZMVD9Y nil} {AWS_SECRET_ACCESS_KEY 3R48ezeISwmbXYc5mzm0vuzgk0BHTUQCbJzVV3RQ nil}]","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"info","msg":"Mount additional volumes: []","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"syncing roles","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"closing database connection","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"syncing databases","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"closing database connection","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"syncing prepared databases with schemas","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"syncing connection pooler (master, replica) from (true, false) to (true, false)","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"final load balancer source ranges as seen in a service spec (not necessarily applied): [\"10.0.0.0/8\"]","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"info","msg":"master service tc-postgres/acid-transcoding-pooler is not in the desired state and needs to be updated","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- protocol: TCP,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- targetPort: 5432,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- nodePort: 31098","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"+ targetPort: 5432","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- clusterIP: 10.43.56.237,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- clusterIPs: [","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- 10.43.56.237","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- ],","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- sessionAffinity: None,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- externalTrafficPolicy: Cluster,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- ipFamilies: [","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- IPv4","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- ],","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- ipFamilyPolicy: SingleStack,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- allocateLoadBalancerNodePorts: true,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"- internalTrafficPolicy: Cluster","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"debug","msg":"+ externalTrafficPolicy: Cluster","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"info","msg":"reason: new service's annotations does not match the current one: Removed \"field.cattle.io/publicEndpoints\".","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"info","msg":"master service \"tc-postgres/acid-transcoding-pooler\" is in the desired state now","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"tc-postgres/acid-transcoding","level":"info","msg":"cluster has been synced","pkg":"controller","time":"2022-11-11T15:45:16Z","worker":1}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"making GET http request: http://10.42.13.3:8008/patroni","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"making GET http request: http://10.42.52.198:8008/patroni","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"making GET http request: http://10.42.175.61:8008/patroni","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"syncing pod disruption budgets","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
W1111 15:45:16.637252 1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"syncing logical backup job","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
W1111 15:45:16.644624 1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"Generating logical backup pod template","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"Generated logical backup env vars","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"[{SCOPE acid-new-polling nil} {CLUSTER_NAME_LABEL cluster-name nil} {POD_NAMESPACE \u0026EnvVarSource{FieldRef:\u0026ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {LOGICAL_BACKUP_PROVIDER s3 nil} {LOGICAL_BACKUP_S3_BUCKET postres-operator-k8s nil} {LOGICAL_BACKUP_S3_REGION us-east-1 nil} {LOGICAL_BACKUP_S3_ENDPOINT https://s3.wasabisys.com nil} {LOGICAL_BACKUP_S3_SSE AES256 nil} {LOGICAL_BACKUP_S3_RETENTION_TIME 90 days nil} {LOGICAL_BACKUP_S3_BUCKET_SCOPE_SUFFIX /0299a6d6-270d-4083-aa8c-6f58f6bf9b0f nil} {LOGICAL_BACKUP_GOOGLE_APPLICATION_CREDENTIALS nil} {PG_VERSION 14 nil} {PGPORT 5432 nil} {PGUSER postgres nil} {PGDATABASE postgres nil} {PGSSLMODE require nil} {PGPASSWORD \u0026EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:\u0026SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:postgres.acid-new-polling.credentials.postgresql.acid.zalan.do,},Key:password,Optional:nil,},}} {AWS_ACCESS_KEY_ID B5UEICVGITZHO6ZMVD9Y nil} {AWS_SECRET_ACCESS_KEY 3R48ezeISwmbXYc5mzm0vuzgk0BHTUQCbJzVV3RQ nil}]","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"info","msg":"Mount additional volumes: []","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"syncing roles","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"closing database connection","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"syncing databases","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"closing database connection","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"syncing prepared databases with schemas","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"syncing connection pooler (master, replica) from (true, false) to (true, false)","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"final load balancer source ranges as seen in a service spec (not necessarily applied): [\"10.0.0.0/8\"]","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"info","msg":"master service polling/acid-new-polling-pooler is not in the desired state and needs to be updated","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- protocol: TCP,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- targetPort: 5432,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- nodePort: 31682","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"+ targetPort: 5432","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- clusterIP: 10.43.204.57,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- clusterIPs: [","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- 10.43.204.57","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- ],","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- sessionAffinity: None,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- externalTrafficPolicy: Cluster,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- ipFamilies: [","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- IPv4","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- ],","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- ipFamilyPolicy: SingleStack,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- allocateLoadBalancerNodePorts: true,","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"- internalTrafficPolicy: Cluster","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"debug","msg":"+ externalTrafficPolicy: Cluster","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"info","msg":"reason: new service's annotations does not match the current one: Removed \"field.cattle.io/publicEndpoints\".","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"info","msg":"master service \"polling/acid-new-polling-pooler\" is in the desired state now","pkg":"cluster","time":"2022-11-11T15:45:16Z","worker":0}
{"cluster-name":"polling/acid-new-polling","level":"info","msg":"cluster has been synced","pkg":"controller","time":"2022-11-11T15:45:16Z","worker":0}
```

**Comment by jonathon2nd** [comment]
Going and checking the S3 bucket, it does look like wal shipping is broken.

Last ones received were 4 days ago, I am guessing the first time it crashed.

**Comment by jonathon2nd** [comment]
OK I confirmed that WAL shipping is working, so it is just the replica dying for the reason listed above.

**Comment by jonathon2nd** [comment]
This is still happening to cluster we create with the operator. Has anyone else even encountered this?

**Comment by jonathon2nd** [comment]
Hey we got this figured out!

It was DRBD. We are using linstor csi in k8s connecting to out linstor cluster. We dug into the kernel messages and found the issue. Updating DRBD solved it.

https://github.com/LINBIT/drbd/blob/1c9d7d5675b45102770db0798e408887b3135fc9/ChangeLog#L30

In case anyone else ever runs into this, we updated from 9.1.11 to 9.2.1.
