### ISSUE TITLE
Even for a single replica cluster Leader election takes place

### ISSUE THREAD

**Issue by Arun-Trichy** [zalando/postgres-operator#2120]
- **Which image of the operator are you using? **registry.opensource.zalan.do/acid/postgres-operator:v1.8.2**
- **Where do you run it - cloud or metal? Kubernetes or OpenShift? **Kubernetes Cluster v1.24 running on-prem**
- **Are you running Postgres Operator in production? No
- **Type of issue? Question/Bug

We are currently running a one replica setup of postgres instance using zalando and could observe that when K8S API server goes down as mentioned here https://github.com/zalando/postgres-operator/issues/354 it goes into Read only mode.
Our concern here is even when running a one node replica why is there a leader election mechanism/ connectivity to K8S API server?
Also is there any way to overcome this, as our production setup only requires one replica setup for now.

Please find the log snippets of our ERRORS attached below:
> 2022-11-29 09:41:09.919 26 LOG {ticks: 0, maint: 0, retry: 0}
2022-11-29 09:41:11,637 INFO: Lock owner: eis-dicom-postgres-0; I am eis-dicom-postgres-0
2022-11-29 09:41:12,246 INFO: no action.  i am the leader with the lock
2022-11-29 09:41:21,637 INFO: Lock owner: eis-dicom-postgres-0; I am eis-dicom-postgres-0
2022-11-29 09:41:32,011 WARNING: Retry got exception: HTTPSConnectionPool(host='11.0.0.1', port=443): Read timed out. (read timeout=4.995480387005955)
2022-11-29 09:41:32,011 ERROR: failed to update leader lock
2022-11-29 09:41:37,079 INFO: demoted self because failed to update leader lock in DCS
2022-11-29 09:41:37,080 INFO: closed patroni connection to the postgresql cluster
2022-11-29 09:41:37,081 WARNING: Loop time exceeded, rescheduling immediately.

> 2022-11-29 09:42:26,926 INFO: Could not take out TTL lock
2022-11-29 09:42:27,427 INFO: following new leader after trying and failing to obtain lock
2022-11-29 09:42:27,460 INFO: Could not take out TTL lock
2022-11-29 09:42:27,468 INFO: following new leader after trying and failing to obtain lock
2022-11-29 09:42:37,930 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0c64ceac18>: Failed to establish a new connection: [Errno 111] Connection refused',)'...

> 2022-11-29 09:46:15,022 INFO: Could not take out TTL lock
2022-11-29 09:46:15,031 INFO: following new leader after trying and failing to obtain lock
2022-11-29 09:46:15,032 WARNING: Loop time exceeded, rescheduling immediately.
2022-11-29 09:46:23,698 ERROR: Unexpected error from Kubernetes API
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 691, in patch_or_create
    return self._patch_or_create(name, annotations, resource_version, patch, retry, ips)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 682, in _patch_or_create
    ret = retry(func, self._namespace, body) if retry else func(self._namespace, body)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 485, in retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/utils.py", line 333, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 296, in wrapper
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 236, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 205, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 174, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'dae1ccd5-9634-4585-9ebf-e8b9f5fc18c6', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 29 Nov 2022 09:46:23 GMT', 'Content-Length': '129'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}\n'

> 2022-11-29 09:54:20,975 WARNING: Loop time exceeded, rescheduling immediately.
2022-11-29 09:54:31,973 WARNING: Retry got exception: HTTPSConnectionPool(host='11.0.0.1', port=443): Read timed out. (read timeout=2.5)
2022-11-29 09:54:31,973 INFO: Could not take out TTL lock
2022-11-29 09:54:40.227 26 LOG {ticks: 0, maint: 0, retry: 0}
2022-11-29 09:54:41,974 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 528, in _load_cluster
    self._wait_caches()
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 522, in _wait_caches
    raise RetryFailedError('Exceeded retry deadline')
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2022-11-29 09:54:41,974 ERROR: Error communicating with DCS
2022-11-29 09:54:41,975 INFO: DCS is not accessible

**Comment by FxKu** [comment]
Enable Patroni failsafe_mode to deal with DCS outage.
