### ISSUE TITLE
Cannot execute SQL commands in WAL sender for physical replication

### ISSUE THREAD

**Issue by jonathon2nd** [zalando/postgres-operator#2151]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** On-prem, Rancher, RKE2, Kubernetes Version: v1.24.4
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** [Bug report, question, feature request, etc.] Bug

Attempting to setup standby cluster in preperation to migrate away from bitnami/postgresql-ha on another cluster. Using same psql version, and have user+passwords setup correctly. 

Attempting to setup standby results in the following on the new pod
```
pg_receivewal: not renaming "0000001A00000014000000CC.partial", segment is not complete
pg_receivewal: error: unexpected termination of replication stream: FATAL: unable to read data from DB node 1
DETAIL: EOF encountered with backend
pg_receivewal: disconnected; waiting 5 seconds to try again
```

Error from the origin cluster
```
ERROR: cannot execute SQL commands in WAL sender for physical replication
LOG: terminating walsender process due to replication timeout
STATEMENT: START_REPLICATION 14/C6000000 TIMELINE 26
LOG: terminating walsender process due to replication timeout
STATEMENT: START_REPLICATION 14/C6000000 TIMELINE 26
LOG: terminating walsender process due to replication timeout
STATEMENT: START_REPLICATION 14/C6000000 TIMELINE 26
ERROR: cannot execute SQL commands in WAL sender for physical replication
```

I have seen https://github.com/zalando/patroni/issues/1979 and https://github.com/zalando/patroni/issues/1989, but as this is a docker image unsure of how to proceed.

**Comment by jonathon2nd** [comment]
been tinkering around and retrying, just got this result with seamingly no change. 

```

2022-12-29 22:52:05,134 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
2022-12-29 22:52:07,139 - bootstrapping - INFO - Could not connect to 169.254.169.254, assuming local Docker setup
2022-12-29 22:52:07,141 - bootstrapping - INFO - No meta-data available for this provider
2022-12-29 22:52:07,141 - bootstrapping - INFO - Looks like your running local
2022-12-29 22:52:07,202 - bootstrapping - INFO - Configuring bootstrap
2022-12-29 22:52:07,202 - bootstrapping - INFO - Configuring standby-cluster
2022-12-29 22:52:07,202 - bootstrapping - INFO - Configuring crontab
2022-12-29 22:52:07,202 - bootstrapping - INFO - Skipping creation of renice cron job due to lack of SYS_NICE capability
2022-12-29 22:52:07,213 - bootstrapping - INFO - Configuring log
2022-12-29 22:52:07,213 - bootstrapping - INFO - Configuring pam-oauth2
2022-12-29 22:52:07,213 - bootstrapping - INFO - Writing to file /etc/pam.d/postgresql
2022-12-29 22:52:07,214 - bootstrapping - INFO - Configuring wal-e
2022-12-29 22:52:07,214 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALE_S3_PREFIX
2022-12-29 22:52:07,215 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_S3_PREFIX
2022-12-29 22:52:07,215 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_ACCESS_KEY_ID
2022-12-29 22:52:07,215 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_SECRET_ACCESS_KEY
2022-12-29 22:52:07,216 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALE_S3_ENDPOINT
2022-12-29 22:52:07,216 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_ENDPOINT
2022-12-29 22:52:07,216 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_REGION
2022-12-29 22:52:07,216 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALE_DISABLE_S3_SSE
2022-12-29 22:52:07,217 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_DISABLE_S3_SSE
2022-12-29 22:52:07,217 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_S3_FORCE_PATH_STYLE
2022-12-29 22:52:07,217 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_DOWNLOAD_CONCURRENCY
2022-12-29 22:52:07,218 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_UPLOAD_CONCURRENCY
2022-12-29 22:52:07,218 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/USE_WALG_BACKUP
2022-12-29 22:52:07,218 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/USE_WALG_RESTORE
2022-12-29 22:52:07,219 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALE_LOG_DESTINATION
2022-12-29 22:52:07,219 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/PGPORT
2022-12-29 22:52:07,219 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/BACKUP_NUM_TO_RETAIN
2022-12-29 22:52:07,220 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/TMPDIR
2022-12-29 22:52:07,221 - bootstrapping - INFO - Configuring pgbouncer
2022-12-29 22:52:07,221 - bootstrapping - INFO - No PGBOUNCER_CONFIGURATION was specified, skipping
2022-12-29 22:52:07,221 - bootstrapping - INFO - Configuring certificate
2022-12-29 22:52:07,221 - bootstrapping - INFO - Generating ssl self-signed certificate
2022-12-29 22:52:07,388 - bootstrapping - INFO - Configuring patroni
2022-12-29 22:52:07,408 - bootstrapping - INFO - Writing to file /run/postgres.yml
2022-12-29 22:52:07,409 - bootstrapping - INFO - Configuring pgqd
2022-12-29 22:52:08,714 WARNING: Kubernetes RBAC doesn't allow GET access to the 'kubernetes' endpoint in the 'default' namespace. Disabling 'bypass_api_service'.
2022-12-29 22:52:08,736 INFO: No PostgreSQL configuration items changed, nothing to reload.
2022-12-29 22:52:08,742 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:52:08,878 INFO: trying to bootstrap a new standby leader
1024+0 records in
1024+0 records out
16777216 bytes (17 MB, 16 MiB) copied, 0.0119498 s, 1.4 GB/s
2022-12-29 22:52:19,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:52:19,242 INFO: not healthy enough for leader race
2022-12-29 22:52:19,316 INFO: bootstrap_standby_leader in progress
2022-12-29 22:52:29,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:52:29,241 INFO: not healthy enough for leader race
2022-12-29 22:52:29,241 INFO: bootstrap_standby_leader in progress
2022-12-29 22:52:39,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:52:39,241 INFO: not healthy enough for leader race
2022-12-29 22:52:39,241 INFO: bootstrap_standby_leader in progress
2022-12-29 22:52:49,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:52:49,241 INFO: not healthy enough for leader race
2022-12-29 22:52:49,241 INFO: bootstrap_standby_leader in progress
2022-12-29 22:52:59,251 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:52:59,251 INFO: not healthy enough for leader race
2022-12-29 22:52:59,251 INFO: bootstrap_standby_leader in progress
2022-12-29 22:53:09,242 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:53:09,242 INFO: not healthy enough for leader race
2022-12-29 22:53:09,242 INFO: bootstrap_standby_leader in progress
pg_receivewal: not renaming "0000001A00000014000000DE.partial", segment is not complete
pg_receivewal: error: unexpected termination of replication stream: FATAL: unable to read data from DB node 1
DETAIL: EOF encountered with backend
pg_receivewal: disconnected; waiting 5 seconds to try again
2022-12-29 22:53:19,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:53:19,241 INFO: not healthy enough for leader race
2022-12-29 22:53:19,241 INFO: bootstrap_standby_leader in progress
2022-12-29 22:53:29,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:53:29,241 INFO: not healthy enough for leader race
2022-12-29 22:53:29,241 INFO: bootstrap_standby_leader in progress
2022-12-29 22:53:39,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:53:39,241 INFO: not healthy enough for leader race
2022-12-29 22:53:39,241 INFO: bootstrap_standby_leader in progress
2022-12-29 22:53:49,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:53:49,241 INFO: not healthy enough for leader race
2022-12-29 22:53:49,241 INFO: bootstrap_standby_leader in progress
2022-12-29 22:53:59,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:53:59,241 INFO: not healthy enough for leader race
2022-12-29 22:53:59,242 INFO: bootstrap_standby_leader in progress
2022-12-29 22:54:09,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:54:09,241 INFO: not healthy enough for leader race
2022-12-29 22:54:09,241 INFO: bootstrap_standby_leader in progress
pg_receivewal: not renaming "0000001A00000014000000DE.partial", segment is not complete
pg_receivewal: error: unexpected termination of replication stream: FATAL: unable to read data from DB node 1
DETAIL: EOF encountered with backend
pg_receivewal: disconnected; waiting 5 seconds to try again
2022-12-29 22:54:19,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:54:19,241 INFO: not healthy enough for leader race
2022-12-29 22:54:19,241 INFO: bootstrap_standby_leader in progress
2022-12-29 22:54:29,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:54:29,241 INFO: not healthy enough for leader race
2022-12-29 22:54:29,241 INFO: bootstrap_standby_leader in progress
2022-12-29 22:54:39,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:54:39,241 INFO: not healthy enough for leader race
2022-12-29 22:54:39,241 INFO: bootstrap_standby_leader in progress
2022-12-29 22:54:49,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:54:49,241 INFO: not healthy enough for leader race
2022-12-29 22:54:49,241 INFO: bootstrap_standby_leader in progress
2022-12-29 22:54:59,241 INFO: Lock owner: None; I am acid-labs-0
2022-12-29 22:54:59,241 INFO: not healthy enough for leader race
2022-12-29 22:54:59,241 INFO: bootstrap_standby_leader in progress
```


Origin cluster
```
Thu, Dec 29 2022 2:53:10 pm | 2022-12-29 22:53:10.245 GMT [17148] STATEMENT: START_REPLICATION 14/DE000000 TIMELINE 26
Thu, Dec 29 2022 2:54:15 pm | 2022-12-29 22:54:15.455 GMT [17333] LOG: terminating walsender process due to replication timeout
Thu, Dec 29 2022 2:54:15 pm | 2022-12-29 22:54:15.455 GMT [17333] STATEMENT: START_REPLICATION 14/DE000000 TIMELINE 26
Thu, Dec 29 2022 2:55:20 pm | 2022-12-29 22:55:20.815 GMT [17528] LOG: terminating walsender process due to replication timeout
Thu, Dec 29 2022 2:55:20 pm | 2022-12-29 22:55:20.815 GMT [17528] STATEMENT: START_REPLICATION 14/DE000000 TIMELINE 26
```

Going to try to increase `wal_sender_timeout`

**Comment by jonathon2nd** [comment]
Increased it, still can't get through
```
Thu, Dec 29 2022 3:22:45 pm | 2022-12-29 23:22:45,097 INFO: not healthy enough for leader race
Thu, Dec 29 2022 3:22:45 pm | 2022-12-29 23:22:45,097 INFO: bootstrap_standby_leader in progress
Thu, Dec 29 2022 3:22:46 pm | pg_receivewal: error: could not send replication command "START_REPLICATION": server closed the connection unexpectedly
Thu, Dec 29 2022 3:22:46 pm | This probably means the server terminated abnormally
Thu, Dec 29 2022 3:22:46 pm | before or while processing the request.
Thu, Dec 29 2022 3:22:46 pm | pg_receivewal: disconnected; waiting 5 seconds to try again
Thu, Dec 29 2022 3:22:55 pm | 2022-12-29 23:22:55,097 INFO: Lock owner: None; I am acid-labs-0
Thu, Dec 29 2022 3:22:55 pm | 2022-12-29 23:22:55,097 INFO: not healthy enough for leader race
Thu, Dec 29 2022 3:22:55 pm | 2022-12-29 23:22:55,097 INFO: bootstrap_standby_leader in progress
Thu, Dec 29 2022 3:23:05 pm | 2022-12-29 23:23:05,096 INFO: Lock owner: None; I am acid-labs-0
```


origin cluster
pgpool
```
Thu, Dec 29 2022 3:19:44 pm | 2022-12-29 23:19:44.860: pg_basebackup pid 8264: LOG: Unable to parse the query: "IDENTIFY_SYSTEM" from client 10.2.3.0(3595)
Thu, Dec 29 2022 3:19:44 pm | 2022-12-29 23:19:44.862: pg_basebackup pid 8264: LOG: Unable to parse the query: "BASE_BACKUP LABEL 'pg_basebackup base backup' PROGRESS MANIFEST 'yes' " from client 10.2.3.0(3595)
Thu, Dec 29 2022 3:19:46 pm | 2022-12-29 23:19:46.005: pg_receivewal pid 9885: LOG: Unable to parse the query: "IDENTIFY_SYSTEM" from client 51-161-81-97.rancher-monitoring-kubelet.kube-system.svc.cluster.local(6619)
Thu, Dec 29 2022 3:19:46 pm | 2022-12-29 23:19:46.048: pg_receivewal pid 9885: LOG: Unable to parse the query: "IDENTIFY_SYSTEM" from client 51-161-81-97.rancher-monitoring-kubelet.kube-system.svc.cluster.local(6619)
Thu, Dec 29 2022 3:19:46 pm | 2022-12-29 23:19:46.069: pg_receivewal pid 9885: LOG: Unable to parse the query: "TIMELINE_HISTORY 26" from client 51-161-81-97.rancher-monitoring-kubelet.kube-system.svc.cluster.local(6619)
Thu, Dec 29 2022 3:19:46 pm | 2022-12-29 23:19:46.103: pg_receivewal pid 9885: LOG: Unable to parse the query: "START_REPLICATION 14/E1000000 TIMELINE 26" from client 51-161-81-97.rancher-monitoring-kubelet.kube-system.svc.cluster.local(6619)
Thu, Dec 29 2022 3:20:06 pm | 2022-12-29 23:20:06.599: TF8 pid 216: ERROR: authentication failed
Thu, Dec 29 2022 3:20:06 pm | 2022-12-29 23:20:06.599: TF8 pid 216: DETAIL: username "postgres" or password does not exist in backend
Thu, Dec 29 2022 3:21:24 pm | 2022-12-29 23:21:24.340: pg_receivewal pid 214: ERROR: unable to write data to frontend
Thu, Dec 29 2022 3:21:24 pm | 2022-12-29 23:21:24.340: pg_receivewal pid 214: DETAIL: pool_flush failed
Thu, Dec 29 2022 3:21:24 pm | 2022-12-29 23:21:24.351: pg_receivewal pid 214: WARNING: write on backend 1 failed with error :"Broken pipe"
Thu, Dec 29 2022 3:21:24 pm | 2022-12-29 23:21:24.351: pg_receivewal pid 214: DETAIL: while trying to write data from offset: 0 wlen: 5
Thu, Dec 29 2022 3:21:31 pm | 2022-12-29 23:21:31.342: dis pid 226: ERROR: unable to read data from frontend
Thu, Dec 29 2022 3:21:31 pm | 2022-12-29 23:21:31.342: dis pid 226: DETAIL: EOF encountered with frontend
Thu, Dec 29 2022 3:22:51 pm | 2022-12-29 23:22:51.260: pg_receivewal pid 168: LOG: Unable to parse the query: "IDENTIFY_SYSTEM" from client 10.2.3.0(64715)
Thu, Dec 29 2022 3:22:51 pm | 2022-12-29 23:22:51.274: pg_receivewal pid 168: LOG: Unable to parse the query: "START_REPLICATION 14/E1000000 TIMELINE 26" from client 10.2.3.0(64715)
```

node-1
```
Thu, Dec 29 2022 3:21:24 pm | 2022-12-29 23:21:24.336 GMT [21626] FATAL: invalid standby message type "Q"
Thu, Dec 29 2022 3:21:24 pm | 2022-12-29 23:21:24.336 GMT [21626] STATEMENT: START_REPLICATION 14/DF000000 TIMELINE 26
```

**Comment by jonathon2nd** [comment]
OK so pgpool was being a pain, so connecting directly to a replica on the source cluster.

Got all the way through, then the pod that the operator made failed.
```
2022-12-30 19:21:12,108 INFO: not healthy enough for leader race
--
Fri, Dec 30 2022 11:21:12 am | 2022-12-30 19:21:12,108 INFO: bootstrap_standby_leader in progress
Fri, Dec 30 2022 11:21:16 am | 2022-12-30 19:21:16,024 INFO: replica has been created using basebackup_fast_xlog
Fri, Dec 30 2022 11:21:16 am | 2022-12-30 19:21:16,027 INFO: bootstrapped clone from remote master postgresql://51.222.45.82:5432
Fri, Dec 30 2022 11:21:16 am | 2022-12-30 19:21:16,036 ERROR: Exception during execution of long running task bootstrap_standby_leader
Fri, Dec 30 2022 11:21:16 am | Traceback (most recent call last):
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/async_executor.py", line 97, in run
Fri, Dec 30 2022 11:21:16 am | wakeup = func(*args) if args else func()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 288, in bootstrap_standby_leader
Fri, Dec 30 2022 11:21:16 am | result = self.clone(clone_source, msg)
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 244, in clone
Fri, Dec 30 2022 11:21:16 am | return self.state_handler.follow(node_to_follow) is not False
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 903, in follow
Fri, Dec 30 2022 11:21:16 am | ret = self.start(timeout=timeout, block_callbacks=change_role, role=role) or None
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 549, in start
Fri, Dec 30 2022 11:21:16 am | self.config.write_postgresql_conf(configuration)
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/config.py", line 390, in write_postgresql_conf
Fri, Dec 30 2022 11:21:16 am | os.rename(self._postgresql_conf, self._postgresql_base_conf)
Fri, Dec 30 2022 11:21:16 am | FileNotFoundError: [Errno 2] No such file or directory: '/home/postgres/pgdata/pgroot/data/postgresql.conf' -> '/home/postgres/pgdata/pgroot/data/postgresql.base.conf'
Fri, Dec 30 2022 11:21:16 am | /var/run/postgresql:5432 - no response
Fri, Dec 30 2022 11:21:16 am | 2022-12-30 19:21:16,056 INFO: removing initialize key after failed attempt to bootstrap the cluster
Fri, Dec 30 2022 11:21:16 am | 2022-12-30 19:21:16,112 INFO: renaming data directory to /home/postgres/pgdata/pgroot/data_2022-12-30-19-21-16
Fri, Dec 30 2022 11:21:16 am | Traceback (most recent call last):
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/bin/patroni", line 11, in <module>
Fri, Dec 30 2022 11:21:16 am | sys.exit(main())
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 143, in main
Fri, Dec 30 2022 11:21:16 am | return patroni_main()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 135, in patroni_main
Fri, Dec 30 2022 11:21:16 am | abstract_main(Patroni, schema)
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 100, in abstract_main
Fri, Dec 30 2022 11:21:16 am | controller.run()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 105, in run
Fri, Dec 30 2022 11:21:16 am | super(Patroni, self).run()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 59, in run
Fri, Dec 30 2022 11:21:16 am | self._run_cycle()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 108, in _run_cycle
Fri, Dec 30 2022 11:21:16 am | logger.info(self.ha.run_cycle())
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1514, in run_cycle
Fri, Dec 30 2022 11:21:16 am | info = self._run_cycle()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1388, in _run_cycle
Fri, Dec 30 2022 11:21:16 am | return self.post_bootstrap()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1280, in post_bootstrap
Fri, Dec 30 2022 11:21:16 am | self.cancel_initialization()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1273, in cancel_initialization
Fri, Dec 30 2022 11:21:16 am | raise PatroniFatalException('Failed to bootstrap cluster')
Fri, Dec 30 2022 11:21:16 am | patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
Fri, Dec 30 2022 11:21:16 am | /etc/runit/runsvdir/default/patroni: finished with code=1 signal=0
Fri, Dec 30 2022 11:21:16 am | /etc/runit/runsvdir/default/patroni: sleeping 30 seconds
Fri, Dec 30 2022 11:21:46 am | 2022-12-30 19:21:46,662 WARNING: Kubernetes RBAC doesn't allow GET access to the 'kubernetes' endpoint in the 'default' namespace. Disabling 'bypass_api_service'.
Fri, Dec 30 2022 11:21:46 am | 2022-12-30 19:21:46,690 INFO: No PostgreSQL configuration items changed, nothing to reload.
Fri, Dec 30 2022 11:21:46 am | 2022-12-30 19:21:46,693 INFO: Lock owner: None; I am acid-labs-0
Fri, Dec 30 2022 11:21:46 am | 2022-12-30 19:21:46,884 INFO: trying to bootstrap a new standby leader
Fri, Dec 30 2022 11:21:57 am | 2022-12-30 19:21:57,194 INFO: Lock owner: None; I am acid-labs-0
Fri, Dec 30 2022 11:21:57 am | 2022-12-30 19:21:57,194 INFO: not healthy enough for leader race
Fri, Dec 30 2022 11:21:57 am | 2022-12-30 19:21:57,265 INFO: bootstrap_standby_leader in progress
Fri, Dec 30 2022 11:22:07 am | 2022-12-30 19:22:07,193 INFO: Lock owner: None; I am acid-labs-0
```

no errors on source cluster, file is just missing?
```
root@acid-labs-0:/home/postgres# ls /home/postgres/pgdata/pgroot/data/
PG_VERSION            backup_label.old      current_logfiles      pg_commit_ts/         pg_ident.conf         pg_multixact/         pg_replslot/          pg_stat/              pg_subtrans/          pg_twophase/          pg_xact/              standby.signal        
backup_label          base/                 global/               pg_dynshmem/          pg_logical/           pg_notify/            pg_snapshots/         pg_stat_tmp/          pg_tblspc/            pg_wal/               postgresql.auto.conf  
```

**Comment by jonathon2nd** [comment]
OK so pgpool was being a pain, so connecting directly to a replica on the source cluster.

Got all the way through, then the pod that the operator made failed.
```
2022-12-30 19:21:12,108 INFO: not healthy enough for leader race
--
Fri, Dec 30 2022 11:21:12 am | 2022-12-30 19:21:12,108 INFO: bootstrap_standby_leader in progress
Fri, Dec 30 2022 11:21:16 am | 2022-12-30 19:21:16,024 INFO: replica has been created using basebackup_fast_xlog
Fri, Dec 30 2022 11:21:16 am | 2022-12-30 19:21:16,027 INFO: bootstrapped clone from remote master postgresql://<IP>:5432
Fri, Dec 30 2022 11:21:16 am | 2022-12-30 19:21:16,036 ERROR: Exception during execution of long running task bootstrap_standby_leader
Fri, Dec 30 2022 11:21:16 am | Traceback (most recent call last):
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/async_executor.py", line 97, in run
Fri, Dec 30 2022 11:21:16 am | wakeup = func(*args) if args else func()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 288, in bootstrap_standby_leader
Fri, Dec 30 2022 11:21:16 am | result = self.clone(clone_source, msg)
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 244, in clone
Fri, Dec 30 2022 11:21:16 am | return self.state_handler.follow(node_to_follow) is not False
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 903, in follow
Fri, Dec 30 2022 11:21:16 am | ret = self.start(timeout=timeout, block_callbacks=change_role, role=role) or None
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 549, in start
Fri, Dec 30 2022 11:21:16 am | self.config.write_postgresql_conf(configuration)
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/config.py", line 390, in write_postgresql_conf
Fri, Dec 30 2022 11:21:16 am | os.rename(self._postgresql_conf, self._postgresql_base_conf)
Fri, Dec 30 2022 11:21:16 am | FileNotFoundError: [Errno 2] No such file or directory: '/home/postgres/pgdata/pgroot/data/postgresql.conf' -> '/home/postgres/pgdata/pgroot/data/postgresql.base.conf'
Fri, Dec 30 2022 11:21:16 am | /var/run/postgresql:5432 - no response
Fri, Dec 30 2022 11:21:16 am | 2022-12-30 19:21:16,056 INFO: removing initialize key after failed attempt to bootstrap the cluster
Fri, Dec 30 2022 11:21:16 am | 2022-12-30 19:21:16,112 INFO: renaming data directory to /home/postgres/pgdata/pgroot/data_2022-12-30-19-21-16
Fri, Dec 30 2022 11:21:16 am | Traceback (most recent call last):
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/bin/patroni", line 11, in <module>
Fri, Dec 30 2022 11:21:16 am | sys.exit(main())
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 143, in main
Fri, Dec 30 2022 11:21:16 am | return patroni_main()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 135, in patroni_main
Fri, Dec 30 2022 11:21:16 am | abstract_main(Patroni, schema)
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 100, in abstract_main
Fri, Dec 30 2022 11:21:16 am | controller.run()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 105, in run
Fri, Dec 30 2022 11:21:16 am | super(Patroni, self).run()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 59, in run
Fri, Dec 30 2022 11:21:16 am | self._run_cycle()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 108, in _run_cycle
Fri, Dec 30 2022 11:21:16 am | logger.info(self.ha.run_cycle())
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1514, in run_cycle
Fri, Dec 30 2022 11:21:16 am | info = self._run_cycle()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1388, in _run_cycle
Fri, Dec 30 2022 11:21:16 am | return self.post_bootstrap()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1280, in post_bootstrap
Fri, Dec 30 2022 11:21:16 am | self.cancel_initialization()
Fri, Dec 30 2022 11:21:16 am | File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1273, in cancel_initialization
Fri, Dec 30 2022 11:21:16 am | raise PatroniFatalException('Failed to bootstrap cluster')
Fri, Dec 30 2022 11:21:16 am | patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
Fri, Dec 30 2022 11:21:16 am | /etc/runit/runsvdir/default/patroni: finished with code=1 signal=0
Fri, Dec 30 2022 11:21:16 am | /etc/runit/runsvdir/default/patroni: sleeping 30 seconds
Fri, Dec 30 2022 11:21:46 am | 2022-12-30 19:21:46,662 WARNING: Kubernetes RBAC doesn't allow GET access to the 'kubernetes' endpoint in the 'default' namespace. Disabling 'bypass_api_service'.
Fri, Dec 30 2022 11:21:46 am | 2022-12-30 19:21:46,690 INFO: No PostgreSQL configuration items changed, nothing to reload.
Fri, Dec 30 2022 11:21:46 am | 2022-12-30 19:21:46,693 INFO: Lock owner: None; I am acid-labs-0
Fri, Dec 30 2022 11:21:46 am | 2022-12-30 19:21:46,884 INFO: trying to bootstrap a new standby leader
Fri, Dec 30 2022 11:21:57 am | 2022-12-30 19:21:57,194 INFO: Lock owner: None; I am acid-labs-0
Fri, Dec 30 2022 11:21:57 am | 2022-12-30 19:21:57,194 INFO: not healthy enough for leader race
Fri, Dec 30 2022 11:21:57 am | 2022-12-30 19:21:57,265 INFO: bootstrap_standby_leader in progress
Fri, Dec 30 2022 11:22:07 am | 2022-12-30 19:22:07,193 INFO: Lock owner: None; I am acid-labs-0
```

no errors on source cluster, file is just missing?
```
root@acid-labs-0:/home/postgres# ls /home/postgres/pgdata/pgroot/data/
PG_VERSION            backup_label.old      current_logfiles      pg_commit_ts/         pg_ident.conf         pg_multixact/         pg_replslot/          pg_stat/              pg_subtrans/          pg_twophase/          pg_xact/              standby.signal        
backup_label          base/                 global/               pg_dynshmem/          pg_logical/           pg_notify/            pg_snapshots/         pg_stat_tmp/          pg_tblspc/            pg_wal/               postgresql.auto.conf  
```

**Comment by jonathon2nd** [comment]
On and off I have not been able to get this working. I have tried replication from the replica and the master, no different. Same error of `no such file`

**Comment by freedbka** [comment]
I have the same problem when I try to make a replica from ordinary postgres on a virtual machine.

**Comment by MatthiasLohr** [comment]
Any solution for this? Currently struggling with the same problem.

**Comment by viceice** [comment]
Seeing same issue while migrating from `bitnami/postgresql` chart. 😕

I found a workaround by simply doing `touch postgresql.conf` in the bitnami data directory.
