### ISSUE TITLE
SSL Issue every 14h 45min - out of proc exit slots

### ISSUE THREAD

**Issue by S-imo-n** [zalando/postgres-operator#2154]
- **Which image of the operator are you using?** 1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** K8s on Metal
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Request for infomation

Every **14h 45min** we get errors on our DB (see Splunk log below). In the log of the DB it is mentioned as "out of proc exit slots"
It seems the connection between our consumers and the DB is reset in this interval.
Currently it is not causing massive issues, but is more a brainteaser, as what is the root of the behaviour.

**Do you know of something periodically happening in the operator, that could fit our timeframe, or are there default timeouts set, that could match our issue?**

Thank you in advance,
Simon

Splunk log:
   exc_info: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: SSL connection has been closed unexpectedly

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/./service/migration_info_service.py", line 47, in is_live
    connection.scalar('SELECT 1;')
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1262, in scalar
    return self.execute(object_, *multiparams, **params).scalar()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1365, in execute
    return self._exec_driver_sql(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1669, in _exec_driver_sql
    ret = self._execute_context(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL connection has been closed unexpectedly

[SQL: SELECT 1;]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by S-imo-n** [comment]
Timescale Issue: https://github.com/timescale/timescaledb/issues/5233
