### ISSUE TITLE
Spilo failing to start with ObjectCache.run ApiException()

### ISSUE THREAD

**Issue by leonz** [zalando/postgres-operator#2186]
- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
1.8.2, with Spilo spilo-14:2.1-p6

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
Openshift, on AWS hardware

- **Are you running Postgres Operator in production?** [yes | no]
Not yet but trying to.

- **Type of issue?** [Bug report, question, feature request, etc.]
Question

Hi,

I am trying to get Postgres Operator to deploy in the above environment, but the Spilo image is failing to start with the following logs.  I have `KUBERNETES_USE_CONFIGMAPS: 'true'`.  Any suggestions for where I should be looking?, as the logs are very unclear on what might be the issue.

```
+ cert_dir=/home/postgres/certs
+ cert_private_key=/mnt/secrets/certs/key.pem
+ cert_private_key_clone=/home/postgres/certs/key.pem
+ [ -f /mnt/secrets/certs/key.pem ]
+ mkdir /home/postgres/certs
+ cp /mnt/secrets/certs/key.pem /home/postgres/certs/key.pem
+ cp /mnt/secrets/certs/cert.pem /home/postgres/certs/cert.pem
+ cp /mnt/secrets/certs/ca.pem /home/postgres/certs/ca.pem
+ chmod 0600 /home/postgres/certs/key.pem
+ exec /launch.sh init
2023-01-23 15:48:45,851 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
2023-01-23 15:48:45,865 - bootstrapping - INFO - Looks like your running aws
2023-01-23 15:48:45,894 - bootstrapping - INFO - Configuring pgbouncer
2023-01-23 15:48:45,894 - bootstrapping - INFO - No PGBOUNCER_CONFIGURATION was specified, skipping
2023-01-23 15:48:45,894 - bootstrapping - INFO - Configuring certificate
2023-01-23 15:48:45,894 - bootstrapping - INFO - Generating ssl self-signed certificate
2023-01-23 15:48:45,941 - bootstrapping - INFO - Configuring bootstrap
2023-01-23 15:48:45,941 - bootstrapping - INFO - Configuring wal-e
2023-01-23 15:48:45,942 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALE_S3_PREFIX
2023-01-23 15:48:45,942 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_S3_PREFIX
2023-01-23 15:48:45,942 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_ACCESS_KEY_ID
2023-01-23 15:48:45,942 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_SECRET_ACCESS_KEY
2023-01-23 15:48:45,942 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALE_S3_ENDPOINT
2023-01-23 15:48:45,943 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_ENDPOINT
2023-01-23 15:48:45,943 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_REGION
2023-01-23 15:48:45,943 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALE_DISABLE_S3_SSE
2023-01-23 15:48:45,943 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_DISABLE_S3_SSE
2023-01-23 15:48:45,943 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_S3_FORCE_PATH_STYLE
2023-01-23 15:48:45,944 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_DOWNLOAD_CONCURRENCY
2023-01-23 15:48:45,944 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_UPLOAD_CONCURRENCY
2023-01-23 15:48:45,944 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/USE_WALG_BACKUP
2023-01-23 15:48:45,944 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/USE_WALG_RESTORE
2023-01-23 15:48:45,944 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_S3_CA_CERT_FILE
2023-01-23 15:48:45,944 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_LIBSODIUM_KEY
2023-01-23 15:48:45,945 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALE_LOG_DESTINATION
2023-01-23 15:48:45,945 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/PGPORT
2023-01-23 15:48:45,945 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/BACKUP_NUM_TO_RETAIN
2023-01-23 15:48:45,945 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/TMPDIR
2023-01-23 15:48:45,945 - bootstrapping - INFO - Configuring log
2023-01-23 15:48:45,945 - bootstrapping - INFO - Configuring patroni
2023-01-23 15:48:45,954 - bootstrapping - INFO - Writing to file /run/postgres.yml
2023-01-23 15:48:45,954 - bootstrapping - INFO - Configuring pgqd
2023-01-23 15:48:45,954 - bootstrapping - INFO - Configuring standby-cluster
2023-01-23 15:48:45,954 - bootstrapping - INFO - Configuring pam-oauth2
2023-01-23 15:48:45,955 - bootstrapping - INFO - Writing to file /etc/pam.d/postgresql
2023-01-23 15:48:45,955 - bootstrapping - INFO - Configuring crontab
2023-01-23 15:48:45,955 - bootstrapping - INFO - Skipping creation of renice cron job due to lack of SYS_NICE capability
2023-01-23 15:48:47,188 WARNING: Kubernetes RBAC doesn't allow GET access to the 'kubernetes' endpoint in the 'default' namespace. Disabling 'bypass_api_service'.
2023-01-23 15:48:48,197 ERROR: ObjectCache.run ApiException()
2023-01-23 15:48:49,200 ERROR: ObjectCache.run ApiException()
2023-01-23 15:48:50,202 ERROR: ObjectCache.run ApiException()
2023-01-23 15:48:51,205 ERROR: ObjectCache.run ApiException()
2023-01-23 15:48:52,208 ERROR: ObjectCache.run ApiException()
2023-01-23 15:48:53,211 ERROR: ObjectCache.run ApiException()
2023-01-23 15:48:54,214 ERROR: ObjectCache.run ApiException()
2023-01-23 15:48:55,217 ERROR: ObjectCache.run ApiException()
2023-01-23 15:48:56,219 ERROR: ObjectCache.run ApiException()
2023-01-23 15:48:57,191 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 757, in _load_cluster
    self._wait_caches(stop_time)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 749, in _wait_caches
    raise RetryFailedError('Exceeded retry deadline')
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2023-01-23 15:48:57,191 WARNING: Can not get cluster from dcs
```

In the operator I see the errors:

```
ERROR could not restart Postgres in  pod datans/postgres-zalando-0: could not get member data: could not make request: Get \\\"http://100.96.28.199:8008/patroni\\\": dial tcp 100.96.28.199:8008: connect: connection refused
ERROR could not sync cluster: could not sync roles: could not init db connection: could not init db connection: still failing after 8 retries
```

**Comment by dmvolod** [comment]
Hi @leonz 

Seems to some problems with RBAC on OpenShift.
Could you please to provide following structs:
- postgres-pod ClusterRole
- postgres-pod ServiceAccount
- operatorconfiguration.acid.zalan.do postgres-operator

What is the installation method to the OpenShift cluster - manual/helm?

According to this issue #2133 following permissions should be added to the ClusterRole, but seems to ConfigMap mode should work without additional Endpoint permissions

```
endpoints/restricted
endpointslices/restricted
```

**Comment by leonz** [comment]
Right now we are deploying manually. I indeed see that endpoints/restricted and endpointslices/restricted are missing.

clusterrole:
```
[maintuser@ip-100-64-27-36 ~]$ kubectl -n data-polka get clusterrole postgres-pod -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2022-11-07T13:04:34Z"
  name: postgres-pod
  resourceVersion: "492277464"
  uid: cc27b00e-af6f-4fb5-9704-7ca5c18e7443
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
```

service account
```
apiVersion: v1
imagePullSecrets:
- name: postgres-pod-dockercfg-<>
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-11-07T13:04:54Z"
  name: postgres-pod
  namespace: <>
  resourceVersion: "293120046"
  uid: 634cba31-dfb3-4824-9ba0-51a7353db070
secrets:
- name: postgres-pod-token-<>
- name: postgres-pod-dockercfg-<>
```

`operatorconfiguration` is not a resource that we have.

**Comment by dmvolod** [comment]
Seems to some steps are missing. Please find correct RBAC for OpenShift here
https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md#manual-deployment-setup-on-openshift

Also operatorconfiguration.acid.zalan.do CR should be present in the operator deployment namespace and `kubernetes_use_configmaps` should be set to `true`

https://github.com/zalando/postgres-operator/blob/7887ebbbcee853a7d6e1bb5360c63d818179c397/manifests/postgresql-operator-default-configuration.yaml#L17

Please try to install and configure operator with helm chart and `.Values.configGeneral.kubernetes_use_configmaps` set to `true`  (not enabled by default)
https://github.com/zalando/postgres-operator/blob/7887ebbbcee853a7d6e1bb5360c63d818179c397/charts/postgres-operator/values.yaml#L46-L47

**Comment by leonz** [comment]
This was resolved after using the right RBAC configurations.

Thanks!
