### ISSUE TITLE
Issues with postgres-ui-operator v1.10.0

### ISSUE THREAD

**Issue by basaveswar-kureti** [zalando/postgres-operator#2302]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** postgres-ui-operator:v1.10.0
- **Where do you run it - cloud or metal?** Bare Metal K8s
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug

Getting the following error in 1.10 for postgres-ui-operator. UI is also not loading.
1.9 is good.

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/handlers.py", line 978, in emit
    self.socket.send(msg)
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
  File "/usr/lib/python3.9/site-packages/gevent/_socket3.py", line 55, in _dummy
    raise OSError(EBADF, 'Bad file descriptor')
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/handlers.py", line 899, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 628, in connect
    raise _SocketError(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/handlers.py", line 981, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.9/logging/handlers.py", line 910, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 628, in connect
    raise _SocketError(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/operator_ui/__main__.py", line 3, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/operator_ui/main.py", line 1145, in main
    logger.info(f'Listening on :{port}')
Message: 'Listening on :8081'
```

**Comment by FxKu** [comment]
Hm,
for me it's working. I do see these exceptions too, but it's expected with default config. Was also reported in #937. Not nice - we want to fix it in the next release. I'm curious how it runs for you in 1.9.0... ?

**Comment by basaveswar-kureti** [comment]
Thanks @FxKu for your response. I thought those error messages are relevant to this issue. If that is already covered as part #937 I guess we can ignore it.

Regarding the original issue, I was able to consistently reproduce using the following. Please let me know if you need any specific logs ?

helm install postgres-operator postgres-operator-charts/postgres-operator
helm install postgres-operator-ui postgres-operator-ui-charts/postgres-operator-ui --set service.type="NodePort" --set service.nodePort=9999 --version 1.10.0

**Comment by cloudymax** [comment]
I'm also seeing similar behavior.

using 1.10 the UI loads to a blank screen (happens when using both nodeport and clusterIP with ingress)

rolling back to 1.9 gets the UI working again.

I'm deploying through ArgoCD via Helm, cluster is single-node K3s with the ingress-nginx controller.

## UI Values:

```yaml
# Helm Values:
# https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator-ui/values.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgoperator-ui
spec:
  destination:
    namespace: postgres-operator
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: >-
      https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
    targetRevision: 1.10.0
    chart: postgres-operator-ui
    helm:
      skipCrds: true
      values: |
        envs:
          # IMPORTANT: While operator chart and UI chart are independent, this is the interface between
          # UI and operator API. Insert the service name of the operator API here!
          appUrl: "http://localhost:8081"
          operatorApiUrl: "http://postgres-operator:8080"
          operatorClusterNameLabel: "cluster-name"
          resourcesVisible: "False"
          targetNamespace: "postgres-clusters"
          teams:
            - "team-a"
            - "team-b"
            - "team-c"
        service:
          type: "NodePort"
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/issuer: "letsencrypt-staging"
            kubernetes.io/tls-acme: "true"           
          hosts:
            - host: pg-operator.website.com
              paths: ["/"]
          tls:
            - secretName: pg-operator-tls
              hosts:
                - pg-operator.website.com
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

## Operator Values:

```yaml
# Helm Values:
# https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/values.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgoperator
spec:
  destination:
    namespace: postgres-operator
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://opensource.zalando.com/postgres-operator/charts/postgres-operator'
    targetRevision: 1.10.0
    chart: postgres-operator
    helm:
      skipCrds: true
      values: |
        configLoadBalancer:
          db_hosted_zone: db.website.com
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
```

**Comment by APoniatowski** [comment]
I can confirm that 1.9 works and upgrading to 1.10 breaks it.

browser console errors for v1.10:
```
prism.css:1     Failed to load resource: net::ERR_CONNECTION_REFUSED
prism.js:1     Failed to load resource: net::ERR_CONNECTION_REFUSED
app.js:1     Failed to load resource: net::ERR_CONNECTION_REFUSED
localhost:8081/favicon.png:1     Failed to load resource: net::ERR_CONNECTION_REFUSED 
```

**Comment by basaveswar-kureti** [comment]
@FxKu As others as well confirmed the issue with v1.10, could you check it when you get sometime ?

**Comment by thedatabaseme** [comment]
For me, this only happens when using a service for accessing the pod. When doing a port forward I can access the UI without issues.

**Comment by jynolen** [comment]
Just begining of understand that there is a "default" syslog handler in logging trying to log into "/dev/log" which not exists

**Comment by rahils-mitre** [comment]
@oskar-s9s that doesn't work either- I get a 504

**Comment by Atomique** [comment]
> @cloudymax Try setting your `appUrl` to actual url you use so, in your case - `pg-operator.cloudydev.net`

That worked for me also. I enabled the ingress object with TLS and you need to set the URL to the external URL with HTTPS.

**Comment by DanOPT** [comment]
> > @cloudymax Try setting your `appUrl` to actual url you use so, in your case - `pg-operator.cloudydev.net`
> 
> That worked for me also. I enabled the ingress object with TLS and you need to set the URL to the external URL with HTT

Confirmed. Setting the appUrl and operatorApiUrl works.

**Comment by FxKu** [comment]
@basaveswar-kureti can you check if works again with the latest 1.10.1 release?
