### ISSUE TITLE
When we running standby cluster we must allow connection from postgres user and know it's credentials?

### ISSUE THREAD

**Issue by dragoangel** [zalando/postgres-operator#2720]
- **Which image of the operator are you using?** ghcr.io/zalando/postgres-operator:v1.12.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** no
- **Type of issue?** question

I can't provide postgres password and access to standby replica, as this is different cluster that I not own, I only allowed to replicate it with user I was provided. From what I see there is no way to setup rewind user, or just say to use same standby user for `check_leader_is_not_in_recovery`.

In result I facing next error:
```
2024-08-06 18:02:15,773 ERROR: Exception when working with leader
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/patroni/postgresql/rewind.py", line 79, in check_leader_is_not_in_recovery
    with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/patroni/postgresql/connection.py", line 157, in get_connection_cursor
    conn = psycopg.connect(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/patroni/psycopg.py", line 103, in connect
    ret = _connect(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "main-server", port 5432 failed: FATAL:  password authentication failed for user "postgres"
connection to server at "main-server", port 5432 failed: FATAL:  pg_hba.conf rejects connection for host "myip", user "postgres", database "postgres", no encryption
```

**Comment by dragoangel** [comment]
Also interesting that there is no attempts to use encryption, only "no encryption"

**Comment by dragoangel** [comment]
@FxKu sorry, for pinging you directly, but can you advice on this case, if there any "workarounds" to set rewind user, or can postgres-operator add rewind user as another option that can be "optionally" set? And #2718 is also quite related, if you can help it would be very nice 🙏.

**Comment by dragoangel** [comment]
Also after "manual modification" of `postgres.yaml` I can set rewind user to be same as `replication`, but of course such settings will not persist over restarts.

**Comment by dragoangel** [comment]
```
GRANT EXECUTE ON function pg_catalog.pg_ls_dir(text, boolean, boolean) TO rewind_user;
GRANT EXECUTE ON function pg_catalog.pg_stat_file(text, boolean) TO rewind_user;
GRANT EXECUTE ON function pg_catalog.pg_read_binary_file(text) TO rewind_user;
GRANT EXECUTE ON function pg_catalog.pg_read_binary_file(text, bigint, bigint, boolean) TO rewind_user;
GRANT SELECT ON TABLE pg_catalog.pg_authid TO rewind_user;
```

Will allow to set `super_username` as `rewind_user`. I do not understand why operator using `pg_authid` while it's enouth to use just `pg_roles` table? https://www.postgresql.org/docs/current/catalog-pg-authid.html
