### ISSUE TITLE
No failover when node when primary pod crashes (forced power off)

### ISSUE THREAD

**Issue by elvinasp** [zalando/postgres-operator#556]
Hello,

maybe I misunderstood documentation, but I suppose Patroni should allow to setup 2 node Primary-Secondary cluster. 

**Target environment:** On premises Kubernetes cluster v1.12.4 on 3 nodes. 2 Worker/Master and 1 master only.
**Patroni operator:** installed via supllied Helm chart. I have only changed: `enable_master_load_balancer: "false"`
**Cluster install:** I have used the supplied demo cluster file `minimal-postgres-manifest.yaml` just renamed database and increased size to 10Gi.

Resulting pods:
```
root@docker-node-elvinas-100:~/git/zalando-operator/manifests# kubectl get pods -l application=spilo -L spilo-role -o wide
NAME                READY   STATUS    RESTARTS   AGE   IP               NODE                      NOMINATED NODE   SPILO-ROLE
vi-test-cluster-0   1/1     Running   0          31m   10.234.31.178    docker-node-elvinas-101   <none>           master
vi-test-cluster-1   1/1     Running   0          14m   10.234.223.193   docker-node-elvinas-102   <none>           replica
root@docker-node-elvinas-100:~/git/zalando-operator/manifests# kubectl get pods -l app.kubernetes.io/name=postgres-operator -o wide
NAME                                         READY   STATUS    RESTARTS   AGE   IP              NODE                      NOMINATED NODE
zalando-postgres-operator-5f6b477bf5-8zq5w   1/1     Running   0          22m   10.234.31.169   docker-node-elvinas-101   <none>
```
Service:
```
root@docker-node-elvinas-100:~/git/zalando-operator/manifests# kubectl get svc -l application=spilo -L spilo-role -o wide
NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE     SELECTOR                                                       SPILO-ROLE
vi-test-cluster          ClusterIP   10.233.155.5     <none>        5432/TCP   3d21h   <none>                                                         master
vi-test-cluster-config   ClusterIP   None             <none>        <none>     3d21h   <none>
vi-test-cluster-repl     ClusterIP   10.233.198.224   <none>        5432/TCP   3d21h   application=spilo,spilo-role=replica,version=vi-test-cluster   replica
```
If I power off worker node with secondary cluster pod as identified by above command I still can access DB via SVC IP. If I simply kill the master pod, cluster either restarts master and resumes from replica or failover to replica seems to be triggered and after short downtime I can access the DB. 

Problem occurs if worker node with primary pod is powered off ( node crash simulated) in this case I do not get failover event and cannot access DB. I have waited for some 5 minutes, which would mean application and environment failure. I have tried to crash "master" node with and without operator running on that node, it makes no difference.

I have run the following loop command to monitor patroni output
`watch -n 1 'for IP in $(kubectl get pods -l application=spilo -L spilo-role -o=custom-columns=IP:.status.podIP --no-headers=true); do curl -m 3 -s http://$IP:8080/patroni | python -m json.tool | grep -E "role|state|pid|query|type"; done'`

So when "primary" node is powered off, master output is soon gone and replica gets stuck at:
```Every 1.0s: for IP in $(kubectl get pods -l application=spilo -L spilo-role ...  docker-node-elvinas-100: Tue May  7 06:16:10 2019

        "role": "replica",
            "pid": 55,
            "state": "S",
            "type": "logger",
            "pid": 56,
            "query": "recovering 000000070000000000000062",
            "state": "D",
            "type": "startup",
            "pid": 60,
            "state": "S",
            "type": "checkpointer",
            "pid": 61,
            "state": "S",
            "type": "bgwriter",
            "pid": 76,
            "state": "S",
            "type": "stats collector",
            "pid": 80,
            "query": "SELECT pg_catalog.pg_create_physical_replication_slot('vi_test_cluster_1', true) WHERE NOT EXISTS (SELECT 1
FROM pg_catalog.pg_replication_slots WHERE slot_type = 'physical' AND slot_name = 'vi_test_cluster_1')",
            "state": "D",
            "type": "backend",
No JSON object could be decoded
``` 

Questions: 
* What configuration dis I miss?
* Or maybe I am trying to achieve technically impossible setup?

Any logs should I dig?
PS'es:
* I have no deep PostgreSQL knowledge. I am just preparing Kubernetes solution with required tools.  
* Chrunchy Data operator seems to have worked with this setup. But it looks like pgo is more suited to offer DB as a service and run lots of instances of same cluster config than to run several custom clusters for "personal" usage.

**Comment by FxKu** [comment]
This seems to be more related to [Patroni](https://github.com/zalando/patroni). Could you provide the logs from Patroni? Simply `kubectl logs` on the replica pod.

**Comment by elvinasp** [comment]
Another test run.  Again killed node with master pod. DB service is in inoperable state. So, which direction to dig further? PostgreSQL was configured with supplied example Patroni demo cluster.

After 15+ minutes cluster is still in inoperable state, although switchover seems to have happened and previous replica _vi-test-cluster-0_ has become master:

```
root@docker-node-elvinas-100:~# kubectl get pods -l application=spilo -L spilo-role -o wide
NAME                READY   STATUS    RESTARTS   AGE     IP               NODE                      NOMINATED NODE   SPILO-ROLE
vi-test-cluster-0   1/1     Running   0          3d22h   10.234.31.191    docker-node-elvinas-101   <none>           master
vi-test-cluster-1   1/1     Unknown   0          3d23h   10.234.223.211   docker-node-elvinas-102   <none>           master
```

PostgreSQL logs became silent with the following last messages:

```
root@docker-node-elvinas-100:~# kubectl exec vi-test-cluster-0 -- tail -n50 -f /home/postgres/pgdata/pgroot/pg_log/postgresql-1.csv /home/postgres/pgdata/pgroot/pg_log/postgresql-1.log
==> /home/postgres/pgdata/pgroot/pg_log/postgresql-1.csv <==
2019-05-13 06:22:16.217 UTC,,,70,,5cd3db19.46,6,,2019-05-09 07:47:37 UTC,1/0,0,LOG,00000,"received promote request",,,,,,,,,""
2019-05-13 06:22:16.218 UTC,,,77,,5cd3db19.4d,2,,2019-05-09 07:47:37 UTC,,0,FATAL,57P01,"terminating walreceiver process due to administrator command",,,,,,,,,""
2019-05-13 06:22:16.221 UTC,,,70,,5cd3db19.46,7,,2019-05-09 07:47:37 UTC,1/0,0,LOG,00000,"redo done at 0/680E0FD0",,,,,,,,,""

==> /home/postgres/pgdata/pgroot/pg_log/postgresql-1.log <==

```

Continuous SQL requests failed once with time out and then SSH simply killed inactive session at ~06:39.

```
while true; do psql -h 10.233.155.5  -U zalando vi -c "select * from pgbench_branches limit 5"; date ; done
......

Mon May 13 06:21:45 UTC 2019
 bid | bbalance | filler
-----+----------+--------
  15 |   277755 |
  30 |  -190945 |
  29 |   -67164 |
   1 |    97939 |
  12 |   -49980 |
(5 rows)

Mon May 13 06:21:45 UTC 2019
 bid | bbalance | filler
-----+----------+--------
  15 |   277755 |
  30 |  -190945 |
  29 |   -67164 |
   1 |    97939 |
  12 |   -49980 |
(5 rows)

Mon May 13 06:21:45 UTC 2019

psql: could not connect to server: Connection timed out
        Is the server running on host "10.233.155.5" and accepting
        TCP/IP connections on port 5432?
Mon May 13 06:23:55 UTC 2019

```

New PostgreSQL master pod logs does not reveal anything new:

```
2019-05-13 06:21:43,968 INFO: Lock owner: vi-test-cluster-1; I am vi-test-cluster-0
2019-05-13 06:21:43,968 INFO: does not have lock
2019-05-13 06:21:43,969 INFO: no action.  i am a secondary and i am following a leader
2019-05-13 06:21:54,001 INFO: Lock owner: vi-test-cluster-1; I am vi-test-cluster-0
2019-05-13 06:21:54,001 INFO: does not have lock
2019-05-13 06:21:54,002 INFO: no action.  i am a secondary and i am following a leader
2019-05-13 06:22:04,039 INFO: Lock owner: vi-test-cluster-1; I am vi-test-cluster-0
2019-05-13 06:22:04,039 INFO: does not have lock
2019-05-13 06:22:04,040 INFO: no action.  i am a secondary and i am following a leader
2019-05-13 06:22:16,080 WARNING: Request failed to vi-test-cluster-1: GET http://10.234.223.211:8008/patroni (HTTPConnectionPool(host='10.234.223.211', port=8008): Max retries exceeded with url: /patroni (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb4283f76a0>, 'Connection to 10.234.223.211 timed out. (connect timeout=2)')))
2019-05-13 06:22:16,201 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
2019-05-13 06:22:16,211 INFO: promoted self to leader by acquiring session lock
server promoting
2019-05-13 06:22:16,217 INFO: cleared rewind state after becoming the leader
2019-05-13 06:22:23,958 INFO: Lock owner: vi-test-cluster-0; I am vi-test-cluster-0
2019-05-13 06:22:23,970 INFO: updated leader lock during promote
2019-05-13 06:22:33,963 INFO: Lock owner: vi-test-cluster-0; I am vi-test-cluster-0
```

At 06:47 UTC node with old master pod was powered back on. New master Postgres logs were updated with the following lines. **Note the time**. I did not see those messages until ~06:4x time, although message timestamp is 06:22-06:27. 

```
==> /home/postgres/pgdata/pgroot/pg_log/postgresql-1.csv <==
==> /home/postgres/pgdata/pgroot/pg_log/postgresql-1.log <==

==> /home/postgres/pgdata/pgroot/pg_log/postgresql-1.csv <==
2019-05-13 06:22:16.221 UTC,,,70,,5cd3db19.46,8,,2019-05-09 07:47:37 UTC,1/0,0,LOG,00000,"last completed transaction was at log time 2019-05-09 07:47:37.657439+00",,,,,,,,,""
2019-05-13 06:22:16.323 UTC,,,2199,"[local]",5cd90d18.897,1,"",2019-05-13 06:22:16 UTC,,0,LOG,00000,"connection received: host=[local]",,,,,,,,,""
2019-05-13 06:22:16.324 UTC,"postgres","postgres",2199,"[local]",5cd90d18.897,2,"authentication",2019-05-13 06:22:16 UTC,4/1,0,LOG,00000,"connection authorized: user=postgres database=postgres",,,,,,,,,""
2019-05-13 06:23:55.539 UTC,,,2212,"10.234.222.192:44434",5cd90d7b.8a4,1,"",2019-05-13 06:23:55 UTC,,0,LOG,00000,"connection received: host=10.234.222.192 port=44434",,,,,,,,,""
2019-05-13 06:23:55.548 UTC,"zalando","vi",2212,"10.234.222.192:44434",5cd90d7b.8a4,2,"authentication",2019-05-13 06:23:55 UTC,5/1,0,LOG,00000,"connection authorized: user=zalando database=vi SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, compression=off)",,,,,,,,,""
2019-05-13 06:27:15.022 UTC,,,2224,"10.234.31.176:58294",5cd90e43.8b0,1,"",2019-05-13 06:27:15 UTC,,0,LOG,00000,"connection received: host=10.234.31.176 port=58294",,,,,,,,,""
2019-05-13 06:27:15.052 UTC,"postgres","postgres",2224,"10.234.31.176:58294",5cd90e43.8b0,2,"authentication",2019-05-13 06:27:15 UTC,6/1,0,LOG,00000,"connection authorized: user=postgres database=postgres SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, compression=off)",,,,,,,,,""
2019-05-13 06:27:15.053 UTC,"postgres","postgres",2224,"10.234.31.176:58294",5cd90e43.8b0,3,"idle",2019-05-13 06:27:15 UTC,,0,LOG,00000,"disconnection: session time: 0:00:00.031 user=postgres database=postgres host=10.234.31.176 port=58294",,,,,,,,,""
2019-05-13 06:27:15.068 UTC,,,2225,"10.234.31.176:58296",5cd90e43.8b1,1,"",2019-05-13 06:27:15 UTC,,0,LOG,00000,"connection received: host=10.234.31.176 port=58296",,,,,,,,,""
2019-05-13 06:27:15.072 UTC,"postgres","postgres",2225,"10.234.31.176:58296",5cd90e43.8b1,2,"authentication",2019-05-13 06:27:15 UTC,6/2,0,LOG,00000,"connection authorized: user=postgres database=postgres SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, compression=off)",,,,,,,,,""
2019-05-13 06:38:19.997 UTC,,,2321,"10.234.222.192:37874",5cd910db.911,1,"",2019-05-13 06:38:19 UTC,,0,LOG,00000,"connection received: host=10.234.222.192 port=37874",,,,,,,,,""
2019-05-13 06:38:20.004 UTC,"zalando","vi",2321,"10.234.222.192:37874",5cd910db.911,2,"authentication",2019-05-13 06:38:19 UTC,7/1,0,LOG,00000,"connection authorized: user=zalando database=vi SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, compression=off)",,,,,,,,,""
2019-05-13 06:49:05.837 UTC,"postgres","postgres",2199,"[local]",5cd90d18.897,3,"SELECT",2019-05-13 06:22:16 UTC,4/0,0,LOG,00000,"duration: 1609512.118 ms  statement: SELECT pg_is_in_recovery()",,,,,,,,,"psql"
2019-05-13 06:49:05.837 UTC,"postgres","postgres",2225,"10.234.31.176:58296",5cd90e43.8b1,3,"PARSE",2019-05-13 06:27:15 UTC,6/3,0,LOG,00000,"duration: 1310763.846 ms  parse <unnamed>: SELECT a.rolname, COALESCE(a.rolpassword, ''), a.rolsuper, a.rolinherit,
                a.rolcreaterole, a.rolcreatedb, a.rolcanlogin, s.setconfig,
                ARRAY(SELECT b.rolname
                      FROM pg_catalog.pg_auth_members m
                      JOIN pg_catalog.pg_authid b ON (m.roleid = b.oid)
                     WHERE m.member = a.oid) as memberof
         FROM pg_catalog.pg_authid a LEFT JOIN pg_db_role_setting s ON (a.oid = s.setrole AND s.setdatabase = 0::oid)
         WHERE a.rolname = ANY($1)
         ORDER BY 1;",,,,,,,,,""
2019-05-13 06:49:05.837 UTC,"postgres","postgres",82,"[local]",5cd3db1a.52,3,"SELECT",2019-05-09 07:47:38 UTC,2/39754,0,ERROR,57014,"canceling statement due to statement timeout",,,,,,"SELECT pg_catalog.pg_create_physical_replication_slot('vi_test_cluster_1', true) WHERE NOT EXISTS (SELECT 1 FROM pg_catalog.pg_replication_slots WHERE slot_type = 'physical' AND slot_name = 'vi_test_cluster_1')",,,"Patroni"
2019-05-13 06:49:05.838 UTC,"postgres","postgres",2199,"[local]",5cd90d18.897,4,"idle",2019-05-13 06:22:16 UTC,,0,LOG,00000,"disconnection: session time: 0:26:49.514 user=postgres database=postgres host=[local]",,,,,,,,,"psql"
.....
```

PostgreSQL pod new master vi-test-cluster-0 logs was updated with the following as node with an old master became online. 

```
2019-05-13 06:49:05,837 INFO: closed patroni connection to the postgresql cluster
2019-05-13 06:49:05,839 ERROR: Failed to create physical replication slot 'vi_test_cluster_1'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql.py", line 483, in _query
    cursor.execute(sql, params)
psycopg2.extensions.QueryCanceledError: canceling statement due to statement timeout


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql.py", line 1626, in sync_replication_slots
    immediately_reserve), name, name)
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql.py", line 497, in _query
    raise PostgresConnectionException('connection problems')
patroni.exceptions.PostgresConnectionException: 'connection problems'
2019-05-13 06:49:05,844 ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/api.py", line 486, in query
    cursor.execute(sql, params)
psycopg2.OperationalError: connection pointer is NULL


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/api.py", line 432, in get_postgresql_status
    self.server.patroni.postgresql.lsn_name), retry=retry)[0]
  File "/usr/local/lib/python3.6/dist-packages/patroni/api.py", line 404, in query
    return self.server.query(sql, *params)
  File "/usr/local/lib/python3.6/dist-packages/patroni/api.py", line 491, in query
    raise PostgresConnectionException('connection problems')
patroni.exceptions.PostgresConnectionException: 'connection problems'
2019-05-13 06:49:05,862 INFO: no action.  i am the leader with the lock
2019-05-13 06:49:05,864 WARNING: Loop time exceeded, rescheduling immediately.
2019-05-13 06:49:05,879 INFO: Lock owner: vi-test-cluster-0; I am vi-test-cluster-0
2019-05-13 06:49:05,879 INFO: establishing a new patroni connection to the postgres cluster
2019-05-13 06:49:06,170 INFO: no action.  i am the leader with the lock
SET
DO
DO
DO
NOTICE:  extension "pg_cron" already exists, skipping
CREATE EXTENSION
NOTICE:  version "1.1" of extension "pg_cron" is already installed
ALTER EXTENSION
ALTER POLICY
```

**Comment by CyberDem0n** [comment]
Is there a `restore_command` set in the recovery.conf?
Does it work at all?

**Comment by elvinasp** [comment]
Not sure if these are the files you were referring to, but there are no restore_command in recovery.conf file. 

Work what?

```root@docker-node-elvinas-100:~# kubectl get pods -l application=spilo -L spilo-role -o wide
NAME                READY   STATUS    RESTARTS   AGE   IP               NODE                      NOMINATED NODE   SPILO-ROLE
vi-test-cluster-0   1/1     Running   0          45h   10.234.223.238   docker-node-elvinas-102   <none>           replica
vi-test-cluster-1   1/1     Running   0          45h   10.234.31.174    docker-node-elvinas-101   <none>           master
root@docker-node-elvinas-100:~# kubectl exec -it vi-test-cluster-0 -- cat /home/postgres/pgdata/pgroot/data/recovery.conf
standby_mode = 'on'
recovery_target_timeline = 'latest'
primary_conninfo = 'user=standby password=*** host=10.234.31.174 port=5432 sslmode=prefer sslcompression=1 application_name=vi-test-cluster-0'
primary_slot_name = 'vi_test_cluster_0'
root@docker-node-elvinas-100:~# kubectl exec -it vi-test-cluster-0 -- cat /home/postgres/pgdata/pgroot/data/recovery.done
standby_mode = 'on'
recovery_target_timeline = 'latest'
primary_conninfo = 'user=standby password=*** host=10.234.223.255 port=5432 sslmode=prefer sslcompression=1 application_name=vi-test-cluster-0'
primary_slot_name = 'vi_test_cluster_0'
root@docker-node-elvinas-100:~# kubectl exec -it vi-test-cluster-1 -- ls -al /home/postgres/pgdata/pgroot/data/
total 180
drwx------ 19 postgres postgres  4096 May 15 00:00 .
drwxr-xr-x  4 postgres postgres  4096 May  3 09:17 ..
-rw-------  1 postgres postgres   177 May 13 08:56 backup_label.old
drwx------  6 postgres postgres  4096 May  3 09:18 base
-rw-r--r--  1 postgres postgres    34 May 15 00:00 current_logfiles
drwx------  2 postgres postgres  4096 May 13 08:57 global
-rw-------  1 postgres postgres   886 May 13 08:56 patroni.dynamic.json
drwx------  2 postgres postgres  4096 May  3 09:18 pg_commit_ts
drwx------  2 postgres postgres  4096 May  3 09:18 pg_dynshmem
-rw-------  1 postgres postgres   641 May 13 08:56 pg_hba.conf
-rw-------  1 postgres postgres   641 May 13 08:56 pg_hba.conf.backup
-rw-------  1 postgres postgres  1636 May 13 08:56 pg_ident.conf
-rw-------  1 postgres postgres  1636 May 13 08:56 pg_ident.conf.backup
drwx------  4 postgres postgres  4096 May 13 09:03 pg_logical
drwx------  4 postgres postgres  4096 May  3 09:18 pg_multixact
drwx------  2 postgres postgres  4096 May 13 08:56 pg_notify
drwx------  3 postgres postgres  4096 May 13 08:57 pg_replslot
drwx------  2 postgres postgres  4096 May  3 09:18 pg_serial
drwx------  2 postgres postgres  4096 May  3 09:18 pg_snapshots
drwx------  2 postgres postgres  4096 May  8 12:33 pg_stat
drwx------  2 postgres postgres  4096 May 15 06:52 pg_stat_tmp
drwx------  2 postgres postgres  4096 May  7 06:11 pg_subtrans
drwx------  2 postgres postgres  4096 May  3 09:18 pg_tblspc
drwx------  2 postgres postgres  4096 May  3 09:18 pg_twophase
-rw-------  1 postgres postgres     3 May  3 09:18 PG_VERSION
drwx------  3 postgres postgres  4096 May 13 08:58 pg_wal
drwx------  2 postgres postgres  4096 May  3 09:18 pg_xact
-rw-------  1 postgres postgres    88 May 13 08:56 postgresql.auto.conf
-rw-------  1 postgres postgres 22846 May 13 08:56 postgresql.base.conf
-rw-------  1 postgres postgres 22846 May 13 08:56 postgresql.base.conf.backup
-rw-r--r--  1 postgres postgres  1838 May 13 08:56 postgresql.conf
-rw-r--r--  1 postgres postgres  1838 May 13 08:56 postgresql.conf.backup
-rw-------  1 postgres postgres   480 May 13 08:56 postmaster.opts
-rw-------  1 postgres postgres   110 May 13 08:57 postmaster.pid
-rw-------  1 postgres postgres   301 May 13 08:56 recovery.done
root@docker-node-elvinas-100:~# kubectl exec -it vi-test-cluster-1 -- cat /home/postgres/pgdata/pgroot/data/recovery.done
standby_mode = 'on'
recovery_target_timeline = 'latest'
primary_conninfo = 'user=standby password=*** host=10.234.222.218 port=5432 sslmode=prefer sslcompression=1 application_name=vi-test-cluster-1'
primary_slot_name = 'vi_test_cluster_1'
```

**Comment by CyberDem0n** [comment]
According to the logs, Patroni acted absolutely as expected. It did a promote, but the postgres was in recovery for another a few minutes. That could happen if the recovery_command is taking too long or if something is wrong with the storage system.
Both cases have nothing to do with Patroni.

**Comment by elvinasp** [comment]
Hello. 

OK, thanks for the help. So this seems to be PSQL internal (or combination with Kubernetes) issue. I guess, I'll leave that for someone more experienced with PSQL. I suspect this is related with Kubernetes as the only change, that triggers failover to fully complete is the response from failed cluster node.

**Comment by FxKu** [comment]
As Patroni does it's job this has to be another issue then. So closing this one for now. But, feel free to reopen when you got new insights. When related to the operator we have to check it out.
