### ISSUE TITLE
Errors during Postgres-operator-ui startup

### ISSUE THREAD

**Issue by yujunz** [zalando/postgres-operator#638]
It seems the caused by the default logging handler

```
/usr/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
operator_ui.cluster_discovery INFO     in cluster configuration failed
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 936, in emit
    self.socket.send(msg)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 390, in send
    return _socket.socket.send(self._sock, data, flags)
OSError: [Errno 9] Bad file descriptor
...
```

**Comment by yujunz** [comment]
Despite the error messages, the UI server is healthy and can be accessed normally.
