### ISSUE TITLE
Changing postgres_superuser breaks bootstrap

### ISSUE THREAD

**Issue by Flowkap** [zalando/postgres-operator#726]
Installing the helm with configmap values and just the 

```
configUsers:
   super_username: "admin"
```
changed to something else then postgres (e.g. admin) the bootstrapping breaks with a shitload of errors.

Using the minimal-manifest with just name changed.

Reinstalling helm with name postgres , nothing else changed works again. So i'm pretty sure its just that one setting (rest is anyway default)

```
[cip-postgres-default-1] ok 
[cip-postgres-default-1] syncing data to disk ... ok 
[cip-postgres-default-1]  
[cip-postgres-default-1] Success. You can now start the database server using: 
[cip-postgres-default-1]  
[cip-postgres-default-1]     /usr/lib/postgresql/11/bin/pg_ctl -D /home/postgres/pgdata/pgroot/data -l logfile start 
[cip-postgres-default-1]  
[cip-postgres-default-1] 2019-11-20 07:53:40,488 INFO: postmaster pid=174 
[cip-postgres-default-1] /var/run/postgresql:5432 - no response 
[cip-postgres-default-1] 2019-11-20 07:53:40 UTC [174]: [1-1] 5dd4f104.ae 0     LOG:  Auto detecting pg_stat_kcache.linux_hz parameter... 
[cip-postgres-default-1] 2019-11-20 07:53:40 UTC [174]: [2-1] 5dd4f104.ae 0     LOG:  pg_stat_kcache.linux_hz is set to 500000 
[cip-postgres-default-1] 2019-11-20 07:53:40 UTC [174]: [3-1] 5dd4f104.ae 0     LOG:  listening on IPv4 address "0.0.0.0", port 5432 
[cip-postgres-default-1] 2019-11-20 07:53:40 UTC [174]: [4-1] 5dd4f104.ae 0     LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432" 
[cip-postgres-default-1] 2019-11-20 07:53:40 UTC [174]: [5-1] 5dd4f104.ae 0     LOG:  redirecting log output to logging collector process 
[cip-postgres-default-1] 2019-11-20 07:53:40 UTC [174]: [6-1] 5dd4f104.ae 0     HINT:  Future log output will appear in directory "../pg_log". 
[cip-postgres-default-1] /var/run/postgresql:5432 - accepting connections 
[cip-postgres-default-1] /var/run/postgresql:5432 - accepting connections 
[cip-postgres-default-1] 2019-11-20 07:53:41,670 INFO: establishing a new patroni connection to the postgres cluster 
[cip-postgres-default-1] 2019-11-20 07:53:41,776 INFO: running post_bootstrap 
[cip-postgres-default-1] SET 
[cip-postgres-default-1] DO 
[cip-postgres-default-1] ERROR:  permission denied to create role 
[cip-postgres-default-1] CONTEXT:  SQL statement "CREATE ROLE zalandos" 
[cip-postgres-default-1] PL/pgSQL function inline_code_block line 7 at SQL statement 
[cip-postgres-default-1] ERROR:  permission denied to create role 
[cip-postgres-default-1] CONTEXT:  SQL statement "CREATE ROLE robot_zmon" 
[cip-postgres-default-1] PL/pgSQL function inline_code_block line 7 at SQL statement 
[cip-postgres-default-1] ERROR:  permission denied to create extension "pg_auth_mon" 
[cip-postgres-default-1] HINT:  Must be superuser to create this extension. 
[cip-postgres-default-1] ERROR:  extension "pg_auth_mon" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.pg_auth_mon" does not exist 
[cip-postgres-default-1] ERROR:  permission denied to create extension "pg_cron" 
[cip-postgres-default-1] HINT:  Must be superuser to create this extension. 
[cip-postgres-default-1] ERROR:  extension "pg_cron" does not exist 
[cip-postgres-default-1] ERROR:  schema "cron" does not exist 
[cip-postgres-default-1] ERROR:  schema "cron" does not exist 
[cip-postgres-default-1] ERROR:  schema "cron" does not exist 
[cip-postgres-default-1] ERROR:  schema "cron" does not exist 
[cip-postgres-default-1] ERROR:  schema "cron" does not exist 
[cip-postgres-default-1] ERROR:  schema "cron" does not exist 
[cip-postgres-default-1] ERROR:  schema "cron" does not exist 
[cip-postgres-default-1] ERROR:  schema "cron" does not exist 
[cip-postgres-default-1] ERROR:  schema "cron" does not exist 
[cip-postgres-default-1] ERROR:  schema "cron" does not exist 
[cip-postgres-default-1] ERROR:  schema "cron" does not exist 
[cip-postgres-default-1] ERROR:  schema "cron" does not exist 
[cip-postgres-default-1] ERROR:  permission denied to create extension "file_fdw" 
[cip-postgres-default-1] HINT:  Must be superuser to create this extension. 
[cip-postgres-default-1] ERROR:  foreign-data wrapper "file_fdw" does not exist 
[cip-postgres-default-1] CONTEXT:  SQL statement "CREATE SERVER pglog FOREIGN DATA WRAPPER file_fdw" 
[cip-postgres-default-1] PL/pgSQL function inline_code_block line 5 at SQL statement 
[cip-postgres-default-1] CREATE TABLE 
[cip-postgres-default-1] GRANT 
[cip-postgres-default-1] ERROR:  server "pglog" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_0" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_0" does not exist 
[cip-postgres-default-1] LINE 3:   FROM public.postgres_log_0 
[cip-postgres-default-1]                ^ 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_0" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_0" does not exist 
[cip-postgres-default-1] ERROR:  server "pglog" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_1" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_1" does not exist 
[cip-postgres-default-1] LINE 3:   FROM public.postgres_log_1 
[cip-postgres-default-1]                ^ 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_1" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_1" does not exist 
[cip-postgres-default-1] ERROR:  server "pglog" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_2" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_2" does not exist 
[cip-postgres-default-1] LINE 3:   FROM public.postgres_log_2 
[cip-postgres-default-1]                ^ 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_2" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_2" does not exist 
[cip-postgres-default-1] ERROR:  server "pglog" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_3" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_3" does not exist 
[cip-postgres-default-1] LINE 3:   FROM public.postgres_log_3 
[cip-postgres-default-1]                ^ 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_3" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_3" does not exist 
[cip-postgres-default-1] ERROR:  server "pglog" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_4" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_4" does not exist 
[cip-postgres-default-1] LINE 3:   FROM public.postgres_log_4 
[cip-postgres-default-1]                ^ 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_4" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_4" does not exist 
[cip-postgres-default-1] ERROR:  server "pglog" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_5" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_5" does not exist 
[cip-postgres-default-1] LINE 3:   FROM public.postgres_log_5 
[cip-postgres-default-1]                ^ 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_5" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_5" does not exist 
[cip-postgres-default-1] ERROR:  server "pglog" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_6" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_6" does not exist 
[cip-postgres-default-1] LINE 3:   FROM public.postgres_log_6 
[cip-postgres-default-1]                ^ 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_6" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_6" does not exist 
[cip-postgres-default-1] ERROR:  server "pglog" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_7" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.postgres_log_7" does not exist 
[cip-postgres-default-1] LINE 3:   FROM public.postgres_log_7 
[cip-postgres-default-1]                ^ 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_7" does not exist 
[cip-postgres-default-1] ERROR:  relation "public.failed_authentication_7" does not exist 
[cip-postgres-default-1] RESET 
[cip-postgres-default-1] ERROR:  role "postgres" does not exist 
[cip-postgres-default-1] NOTICE:  schema "zmon_utils" does not exist, skipping 
[cip-postgres-default-1] DROP SCHEMA 
[cip-postgres-default-1] ERROR:  permission denied to create extension "plpython3u" 
[cip-postgres-default-1] HINT:  Must be superuser to create this extension. 
[cip-postgres-default-1] CONTEXT:  SQL statement "CREATE EXTENSION IF NOT EXISTS plpython3u" 
[cip-postgres-default-1] PL/pgSQL function inline_code_block line 7 at SQL statement 
[cip-postgres-default-1] NOTICE:  language "plpythonu" does not exist, skipping 
[cip-postgres-default-1] DROP LANGUAGE 
[cip-postgres-default-1] NOTICE:  function plpython_call_handler() does not exist, skipping 
[cip-postgres-default-1] DROP FUNCTION 
[cip-postgres-default-1] NOTICE:  function plpython_inline_handler(internal) does not exist, skipping 
[cip-postgres-default-1] DROP FUNCTION 
[cip-postgres-default-1] NOTICE:  function plpython_validator(oid) does not exist, skipping 
[cip-postgres-default-1] DROP FUNCTION 
[cip-postgres-default-1] CREATE SCHEMA 
[cip-postgres-default-1] ERROR:  role "robot_zmon" does not exist 
[cip-postgres-default-1] SET 
[cip-postgres-default-1] CREATE TYPE 
[cip-postgres-default-1] CREATE FUNCTION 
[cip-postgres-default-1] ERROR:  language "plpython3u" does not exist 
[cip-postgres-default-1] HINT:  Use CREATE EXTENSION to load the language into the database. 
[cip-postgres-default-1] ERROR:  role "robot_zmon" does not exist 
[cip-postgres-default-1] \connect: FATAL:  role "admin" is not permitted to log in 
[cip-postgres-default-1] 2019-11-20 07:53:48,151 ERROR: post_init script /scripts/post_init.sh "zalandos" returned non-zero code 2 
[cip-postgres-default-1] 2019-11-20 07:53:48,195 INFO: removing initialize key after failed attempt to bootstrap the cluster 
[cip-postgres-default-1] 2019-11-20 07:53:49,200 INFO reaped unknown pid 174 
[cip-postgres-default-1] 2019-11-20 07:53:49,200 INFO reaped unknown pid 176 
[cip-postgres-default-1] 2019-11-20 07:53:49,226 INFO: renaming data directory to /home/postgres/pgdata/pgroot/data_2019-11-20-07-53-49 
[cip-postgres-default-1] 2019-11-20 07:53:49,521 INFO: Lock owner: None; I am cip-postgres-default-1 
[cip-postgres-default-1] Traceback (most recent call last): 
[cip-postgres-default-1]   File "/usr/local/bin/patroni", line 11, in <module> 
[cip-postgres-default-1]     sys.exit(main()) 
[cip-postgres-default-1]   File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 196, in main 
[cip-postgres-default-1]     return patroni_main() 
[cip-postgres-default-1]   File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 160, in patroni_main 
[cip-postgres-default-1]     patroni.run() 
[cip-postgres-default-1]   File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 125, in run 
[cip-postgres-default-1]     logger.info(self.ha.run_cycle()) 
[cip-postgres-default-1]   File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1344, in run_cycle 
[cip-postgres-default-1]     info = self._run_cycle() 
[cip-postgres-default-1]   File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1253, in _run_cycle 
[cip-postgres-default-1]     return self.post_bootstrap() 
[cip-postgres-default-1]   File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1149, in post_bootstrap 
[cip-postgres-default-1]     self.cancel_initialization() 
[cip-postgres-default-1]   File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1144, in cancel_initialization 
[cip-postgres-default-1]     raise PatroniException('Failed to bootstrap cluster') 
[cip-postgres-default-1] patroni.exceptions.PatroniException: 'Failed to bootstrap cluster' 
[cip-postgres-default-1] 2019-11-20 07:53:49,590 INFO exited: patroni (exit status 1; not expected) 
[cip-postgres-default-1] 2019-11-20 07:53:50,593 INFO spawned: 'patroni' with pid 250 
[cip-postgres-default-1] 2019-11-20 07:53:51,148 INFO: No PostgreSQL configuration items changed, nothing to reload. 
[cip-postgres-default-1] 2019-11-20 07:53:51,180 INFO: Lock owner: None; I am cip-postgres-default-1 
[cip-postgres-default-1] 2019-11-20 07:53:51,220 INFO: trying to bootstrap a new cluster 
[cip-postgres-default-1] The files belonging to this database system will be owned by user "postgres". 
[cip-postgres-default-1] This user must also own the server process. 
[cip-postgres-default-1]  
[cip-postgres-default-1] The database cluster will be initialized with locale "en_US.UTF-8". 
[cip-postgres-default-1] The default text search configuration will be set to "english". 
[cip-postgres-default-1]  
[cip-postgres-default-1] Data page checksums are enabled. 
[cip-postgres-default-1]  
[cip-postgres-default-1] creating directory /home/postgres/pgdata/pgroot/data ... ok 
[cip-postgres-default-1] creating subdirectories ... ok 
[cip-postgres-default-1] selecting default max_connections ... 100 
[cip-postgres-default-1] selecting default shared_buffers ... 128MB 
[cip-postgres-default-1] selecting default timezone ... Etc/UTC 
[cip-postgres-default-1] selecting dynamic shared memory implementation ... posix 
[cip-postgres-default-1] creating configuration files ... ok 
[cip-postgres-default-1] running bootstrap script ... 2019-11-20 07:53:52,550 INFO success: patroni entered RUNNING state, process has stayed up for > than 1 seconds (startsecs) 
```

**Comment by FxKu** [comment]
`admin` is a [protected](https://github.com/zalando/postgres-operator/blob/master/manifests/configmap.yaml#L59) role used by the Spilo image. You must not use it in this context. We should actually document it properly that there are some reserved role names (`postgres`, `admin`, `standby`). Did you get the same errors also with other names?

**Comment by Flowkap** [comment]
Is this related to protected_role_names? Because we use admin as default user everywhere but I can't convince postgres-operator to do so. I actually found to use infrastructure roles to use for additional accounts not tweaking with the default superuser name but even there I get an error for username admin. 

I assume the same root cause is for my initial ticket. Some feedback appreciated. If its really not intended I give the postgres user a different name instead of admin. No prob.

**Comment by FxKu** [comment]
`admin` comes from Spilo - so you have to patch the image then. `protected_role_names` is more meant for additional roles you want to protect, when you've defined some infrastructure roles to be created in each new Postgres cluster.

Btw: "Desired default password"?!!!
