### ISSUE TITLE
Clone error: Operator trying to restore using 'wal-e` instead of `wal-g`

### ISSUE THREAD

**Issue by anshudutta** [zalando/postgres-operator#800]
I have a cluster uploading to GCS using wal-g in kubernetes. When I restored the cluster using the spec

```
 clone:
    uid: 9dc106fa-3a91-11ea-8e59-42010a00000b   # --> Find it in metadata of the cluster
    cluster: "alchemy-database"
    timestamp: "2050-12-19T12:40:33+01:00"      # --> Future represents latest
```
I see the following error
```
2020-01-23 01:22:46,619 INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-01-23 01:22:46,624 INFO: Lock owner: None; I am alchemy-database-0
2020-01-23 01:22:46,670 INFO: trying to bootstrap a new cluster
2020-01-23 01:22:46,670 INFO: Running custom bootstrap script: envdir "/home/postgres/etc/wal-e.d/env-clone-alchemy-database" python3 /scripts/clone_with_wale.py --recovery-target-time="2050-12-19T12:40:33+01:00"
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-list".
        STRUCTURED: time=2020-01-23T01:22:46.952905-00 pid=7113
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python3.6/dist-packages/wal_e/cmd.py", line 627, in main
            backup_cxt.backup_list(query=args.QUERY, detail=args.detail)
          File "/usr/local/lib/python3.6/dist-packages/wal_e/operator/backup.py", line 66, in backup_list
            for bi in bl_iter:
          File "/usr/local/lib/python3.6/dist-packages/wal_e/worker/base.py", line 153, in __iter__
            for key in self._backup_list(self.layout.basebackups()):
          File "/usr/local/lib/python3.6/dist-packages/wal_e/worker/gs/gs_worker.py", line 92, in _backup_list
            bucket = get_bucket(self.conn, self.layout.store_name())
          File "/usr/local/lib/python3.6/dist-packages/wal_e/worker/gs/gs_worker.py", line 26, in get_bucket
            return conn.get_bucket(name)
          File "/usr/local/lib/python3.6/dist-packages/google/cloud/storage/client.py", line 303, in get_bucket
            bucket = self._bucket_arg_to_bucket(bucket_or_name)
          File "/usr/local/lib/python3.6/dist-packages/google/cloud/storage/client.py", line 201, in _bucket_arg_to_bucket
            bucket = Bucket(self, name=bucket_or_name)
          File "/usr/local/lib/python3.6/dist-packages/google/cloud/storage/bucket.py", line 504, in __init__
            name = _validate_name(name)
          File "/usr/local/lib/python3.6/dist-packages/google/cloud/storage/_helpers.py", line 47, in _validate_name
            if not all([name[0].isalnum(), name[-1].isalnum()]):
        IndexError: string index out of range

        STRUCTURED: time=2020-01-23T01:22:47.356925-00 pid=7113
2020-01-23 01:22:47,473 ERROR: Clone failed
Traceback (most recent call last):
  File "/scripts/clone_with_wale.py", line 100, in main
    run_clone_from_s3(options)
  File "/scripts/clone_with_wale.py", line 86, in run_clone_from_s3
    backup_list = subprocess.check_output(backup_list_cmd)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['wal-e', 'backup-list']' returned non-zero exit status 2.
2020-01-23 01:22:47,492 INFO: removing initialize key after failed attempt to bootstrap the cluster
2020-01-23 01:22:47,624 INFO: Lock owner: None; I am alchemy-database-0
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    load_entry_point('patroni==1.6.3', 'console_scripts', 'patroni')()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 221, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 185, in patroni_main
    patroni.run()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 134, in run
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1336, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1244, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1141, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1136, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
```
The config map
```
apiVersion: v1
data:
  CLONE_WALG_GS_PREFIX: gs://pgbucket-rl-8ebf3fa4/spilo/$(CLONE_SCOPE)
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  WALE_BACKUP_THRESHOLD_PERCENTAGE: "100"
  WALG_GS_PREFIX: gs://pgbucket-rl-8ebf3fa4/spilo/$(SCOPE)
kind: ConfigMap
```
What is confusing is this line. Why is it trying to use `wal-e`?
```
subprocess.CalledProcessError: Command '['wal-e', 'backup-list']' returned non-zero exit status 2.
```
When I ssh into the pods, I see that it has the correct env variables to use `wal-g`
```
WALE_ENV_DIR=/home/postgres/etc/wal-e.d/env
WALG_GS_PREFIX=gs://pgbucket-rl-8ebf3fa4/spilo/alchemy-database
ALCHEMY_DATABASE_REPL_PORT_5432_TCP_ADDR=10.22.6.105
ALCHEMY_DATABASE_REPL_SERVICE_PORT=5432
LOGNAME=postgres
USE_WALG_BACKUP=true
PGLOG=/home/postgres/pgdata/pgroot/pg_log
WALE_BACKUP_THRESHOLD_PERCENTAGE=100
```
```
$ wal-g --version
wal-g version v0.2.14	d372cbd	2019.12.04_06:14:06	PostgreSQL
$ patronictl version
patronictl version 1.6.3
```
spilo image: `: registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p16`

**Comment by anshudutta** [comment]
What worked is that you have to specify all env variables with `CLONE_` prefix to work. So the config map now looks 
```
apiVersion: v1
data:
  CLONE_USE_WALG_BACKUP: "true"
  CLONE_USE_WALG_RESTORE: "true"
  CLONE_WALE_BACKUP_THRESHOLD_PERCENTAGE: "100"
  CLONE_WALG_GS_PREFIX: gs://pgbucket-rl-8ebf3fa4/spilo/$(CLONE_SCOPE)
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  WALE_BACKUP_THRESHOLD_PERCENTAGE: "100"
  WALG_GS_PREFIX: gs://pgbucket-rl-8ebf3fa4/spilo/$(SCOPE)
kind: ConfigMap
```
