### ISSUE TITLE
[OpenShift] unexpected error message inside the postgres pod created by the operator

### ISSUE THREAD

**Issue by kashif68** [zalando/postgres-operator#856]
Below is the error message in the pod log:

2020-03-02 22:36:13,579 WARNING: Can not get cluster from dcs
2020-03-02 22:36:18,585 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 146, in _load_cluster
    response = self.retry(self._api.list_namespaced_pod, self._namespace, label_selector=self._label_selector)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 114, in retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/utils.py", line 313, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 50, in wrapper
    return getattr(self._api, func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 13060, in list_namespaced_pod
    (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 13162, in list_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 148, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 371, in request
    headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 250, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 240, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Mon, 02 Mar 2020 22:36:21 GMT', 'Content-Length': '305'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:track-service-dev:postgres-operator\" cannot list pods in the namespace \"track-service-dev\": no RBAC policy matched","reason":"Forbidden","details":{"kind":"pods"},"code":403}

**Comment by dejwsz** [comment]
Maybe it is missing permission in ClusterRole related to "postgres-operator" account? Can you check it?

**Comment by kashif68** [comment]
That's what I thought but it is there and verified details for correctness.
This is for openshift 3.11
there is REST call involved via Patroni and wondering openshift needs ingress stuff

**Comment by kashif68** [comment]
ok. thanks
What is your conclusion so far?

**Comment by dejwsz** [comment]
Well, this operator needs a lot to have it run on Openshift properly, maybe I will back to it later but first I will try other options/operators.

**Comment by dejwsz** [comment]
It looks like Crunchy PostgreSQL Operator is better adopted to Openshift and it seems to work well (I did some tests to prove it on Openshift 3.11). I believe Zalanos's Operator is very good on k8s but in order to use it on Openshift you need some changes and configuration tricks. So I am switching to Crounchy's one.

**Comment by kashif68** [comment]
Ok. Thanks for sharing!
What is your experience so far with getting Crunchy into openshift?

**Comment by dejwsz** [comment]
It's working generally - I tested the latest release 4.2.2 on Openshift 3.11. There are several installation options - I used ansible installer which works very well (you need to clone github operator repo for this). I tried OLM too but it is not so convenient as you have to do a few manual steps.

**Comment by ReSearchITEng** [comment]
It has been tested, and if the RBAC is configured as per docs, there was no issue.
For running in non-root mode:
Operator Image should be at least:  registry.opensource.zalan.do/acid/postgres-operator:v1.4.0-21-g1249626-dirty
Operator should be configured with these values:
  kubernetes_use_configmaps: "true"
  docker_image: registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p114 #or newer

To get the latest versions of the images of both operator and spilo, do:
https://registry.opensource.zalan.do/v2/acid/postgres-operator/tags/list
https://registry.opensource.zalan.do/v2/acid/spilo-cdp-12/tags/list

**Comment by FxKu** [comment]
Thanks @ReSearchITEng for providing infos about rootless Spilo and new operator options. Closing it now.
