### ISSUE TITLE
Operator does not pass role name with v1.5 and minimal CRD

### ISSUE THREAD

**Issue by stephan2012** [zalando/postgres-operator#982]
While trying to run a new minimal cluster with v1.5 (just as depicted on https://github.com/zalando/postgres-operator/blob/master/docs/user.md#create-a-manifest-for-a-new-postgresql-cluster) I'm facing this error with missing role names:

```
2020-05-18 17:43:42,358 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
2020-05-18 17:43:42,364 - bootstrapping - INFO - Could not connect to 169.254.169.254, assuming local Docker setup
2020-05-18 17:43:42,365 - bootstrapping - INFO - No meta-data available for this provider
2020-05-18 17:43:42,365 - bootstrapping - INFO - Looks like your running local
2020-05-18 17:43:42,394 - bootstrapping - INFO - Configuring pam-oauth2
2020-05-18 17:43:42,394 - bootstrapping - INFO - No PAM_OAUTH2 configuration was specified, skipping
2020-05-18 17:43:42,394 - bootstrapping - INFO - Configuring pgbouncer
2020-05-18 17:43:42,394 - bootstrapping - INFO - No PGBOUNCER_CONFIGURATION was specified, skipping
2020-05-18 17:43:42,394 - bootstrapping - INFO - Configuring standby-cluster
2020-05-18 17:43:42,395 - bootstrapping - INFO - Configuring crontab
2020-05-18 17:43:42,395 - bootstrapping - INFO - Skipping creation of renice cron job due to lack of SYS_NICE capability
2020-05-18 17:43:42,395 - bootstrapping - INFO - Configuring pgqd
2020-05-18 17:43:42,395 - bootstrapping - INFO - Configuring wal-e
2020-05-18 17:43:42,395 - bootstrapping - INFO - Configuring bootstrap
2020-05-18 17:43:42,396 - bootstrapping - INFO - Configuring certificate
2020-05-18 17:43:42,396 - bootstrapping - INFO - Generating ssl certificate
2020-05-18 17:43:42,683 - bootstrapping - INFO - Configuring patroni
2020-05-18 17:43:42,694 - bootstrapping - INFO - Writing to file /home/postgres/postgres.yml
2020-05-18 17:43:42,695 - bootstrapping - INFO - Configuring log
2020-05-18 17:43:44,079 INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-05-18 17:43:44,082 INFO: Lock owner: None; I am acid-minimal-test1-0
2020-05-18 17:43:44,121 INFO: waiting for leader to bootstrap
2020-05-18 17:43:54,082 INFO: Lock owner: None; I am acid-minimal-test1-0
2020-05-18 17:43:54,098 INFO: trying to bootstrap a new cluster
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are enabled.

creating directory /home/postgres/pgdata/pgroot/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    /usr/lib/postgresql/11/bin/pg_ctl -D /home/postgres/pgdata/pgroot/data -l logfile start

2020-05-18 17:43:55 UTC [79]: [1-1] 5ec2c95b.4f 0     LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...
2020-05-18 17:43:55 UTC [79]: [2-1] 5ec2c95b.4f 0     LOG:  pg_stat_kcache.linux_hz is set to 1000000
2020-05-18 17:43:55 UTC [79]: [3-1] 5ec2c95b.4f 0     LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-05-18 17:43:55 UTC [79]: [4-1] 5ec2c95b.4f 0     LOG:  listening on IPv6 address "::", port 5432
2020-05-18 17:43:55 UTC [79]: [5-1] 5ec2c95b.4f 0     LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-05-18 17:43:55,331 INFO: postmaster pid=79
2020-05-18 17:43:55 UTC [79]: [6-1] 5ec2c95b.4f 0     LOG:  redirecting log output to logging collector process
2020-05-18 17:43:55 UTC [79]: [7-1] 5ec2c95b.4f 0     HINT:  Future log output will appear in directory "../pg_log".
/var/run/postgresql:5432 - rejecting connections
/var/run/postgresql:5432 - rejecting connections
/var/run/postgresql:5432 - accepting connections
2020-05-18 17:43:56,403 INFO: establishing a new patroni connection to the postgres cluster
2020-05-18 17:43:56,423 INFO: running post_bootstrap
SET
DO
ERROR:  syntax error at or near "WITH"
LINE 5:         ALTER ROLE  WITH NOCREATEDB NOLOGIN NOCREATEROLE NOS...
                            ^
DO
CREATE EXTENSION
NOTICE:  version "1.0" of extension "pg_auth_mon" is already installed
ALTER EXTENSION
GRANT
CREATE EXTENSION
NOTICE:  version "1.2" of extension "pg_cron" is already installed
ALTER EXTENSION
ALTER POLICY
REVOKE
GRANT
GRANT
CREATE FUNCTION
REVOKE
GRANT
REVOKE
GRANT
REVOKE
GRANT
GRANT
CREATE EXTENSION
DO
CREATE TABLE
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
RESET
SET
NOTICE:  schema "zmon_utils" does not exist, skipping
DROP SCHEMA
DO
NOTICE:  language "plpythonu" does not exist, skipping
DROP LANGUAGE
NOTICE:  function plpython_call_handler() does not exist, skipping
DROP FUNCTION
NOTICE:  function plpython_inline_handler(internal) does not exist, skipping
DROP FUNCTION
NOTICE:  function plpython_validator(oid) does not exist, skipping
DROP FUNCTION
CREATE SCHEMA
GRANT
SET
CREATE TYPE
CREATE FUNCTION
CREATE FUNCTION
GRANT
You are now connected to database "postgres" as user "postgres".
CREATE SCHEMA
GRANT
SET
CREATE FUNCTION
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
GRANT
RESET
CREATE EXTENSION
CREATE EXTENSION
CREATE EXTENSION
NOTICE:  version "1.6" of extension "set_user" is already installed
ALTER EXTENSION
GRANT
GRANT
CREATE SCHEMA
GRANT
GRANT
SET
CREATE FUNCTION
REVOKE
GRANT
GRANT
CREATE VIEW
REVOKE
GRANT
GRANT
CREATE FUNCTION
REVOKE
GRANT
GRANT
CREATE VIEW
REVOKE
GRANT
GRANT
CREATE FUNCTION
REVOKE
GRANT
GRANT
CREATE VIEW
REVOKE
GRANT
GRANT
RESET
You are now connected to database "template1" as user "postgres".
CREATE SCHEMA
GRANT
SET
CREATE FUNCTION
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
GRANT
RESET
CREATE EXTENSION
CREATE EXTENSION
CREATE EXTENSION
NOTICE:  version "1.6" of extension "set_user" is already installed
ALTER EXTENSION
GRANT
GRANT
CREATE SCHEMA
GRANT
GRANT
SET
CREATE FUNCTION
REVOKE
GRANT
GRANT
CREATE VIEW
REVOKE
GRANT
GRANT
CREATE FUNCTION
REVOKE
GRANT
GRANT
CREATE VIEW
REVOKE
GRANT
GRANT
CREATE FUNCTION
REVOKE
GRANT
GRANT
CREATE VIEW
REVOKE
GRANT
GRANT
RESET
2020-05-18 17:43:57,066 ERROR: post_bootstrap
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/bootstrap.py", line 349, in post_bootstrap
    self.create_or_update_role(name, value.get('password'), value.get('options', []))
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/bootstrap.py", line 317, in create_or_update_role
    self._postgresql.query(sql, *params)
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 260, in query
    return self.retry(self._query, sql, *args)
  File "/usr/local/lib/python3.6/dist-packages/patroni/utils.py", line 331, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 251, in _query
    raise e
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 240, in _query
    cursor.execute(sql, params)
psycopg2.errors.SyntaxError: zero-length delimited identifier at or near """"
LINE 6:         ALTER ROLE "" WITH CREATEDB NOLOGIN;
                           ^

2020-05-18 17:43:57,068 INFO: removing initialize key after failed attempt to bootstrap the cluster
2020-05-18 17:43:57,129 INFO: renaming data directory to /home/postgres/pgdata/pgroot/data_2020-05-18-17-43-57
2020-05-18 17:43:57,596 INFO: Lock owner: None; I am acid-minimal-test1-0
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    load_entry_point('patroni==1.6.5', 'console_scripts', 'patroni')()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 235, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 199, in patroni_main
    patroni.run()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 135, in run
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1370, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1277, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1173, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1168, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
/run/service/patroni: finished with code=1 signal=0
/run/service/patroni: sleeping 30 seconds
```

Note the missing role name in

```
LINE 5:         ALTER ROLE  WITH NOCREATEDB NOLOGIN NOCREATEROLE NOS...
```

and

```
LINE 6:         ALTER ROLE "" WITH CREATEDB NOLOGIN;
```

This is the CRD:

```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-test1
spec:
  teamId: "acid"
  volume:
    size: 10Gi
    storageClass: local
  numberOfInstances: 2
  users:
    # database owner
    zalando:
    - superuser
    - createdb

    # role for application foo
    foo_user: # or 'foo_user: []'

  #databases: name->owner
  databases:
    foo: zalando
  postgresql:
    version: "11"
```

Probably related to `preparedDatabases`?

**Comment by stephan2012** [comment]
When upgrading a database that was created with operator v1.4, the logs show

```
SET
DO
ERROR:  syntax error at or near "true"
LINE 5:         ALTER ROLE true WITH NOCREATEDB NOLOGIN NOCREATEROLE...
                           ^
```

**Comment by FxKu** [comment]
weird, I think one have to use `foo_user: []` with empty array brackets. Can you try.
Which configuration are you using? I can think of issues with default values in the OperatorConfiguration CRD.

**Comment by stephan2012** [comment]
@FxKu: Changing to `foo_user: []` (empty list) results in the same error:

```
DO
ERROR:  syntax error at or near "WITH"
LINE 5:         ALTER ROLE  WITH NOCREATEDB NOLOGIN NOCREATEROLE NOS...
                            ^
```

Here’s the operator config:

```yaml
apiVersion: acid.zalan.do/v1
kind: OperatorConfiguration
metadata:
  annotations:
    meta.helm.sh/release-name: postgres-operator
    meta.helm.sh/release-namespace: postgres-operator
  creationTimestamp: "2020-05-14T13:24:39Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: postgres-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-1.5.0
  name: postgres-operator
  namespace: postgres-operator
  resourceVersion: "4669"
  selfLink: /apis/acid.zalan.do/v1/namespaces/postgres-operator/operatorconfigurations/postgres-operator
  uid: a244397b-bc34-4727-b028-c1380278fa5dconfiguration:
  aws_or_gcp:
    aws_region: eu-central-1
  connection_pooler:
    connection_pooler_default_cpu_limit: "1"
    connection_pooler_default_cpu_request: 500m
    connection_pooler_default_memory_limit: 100Mi
    connection_pooler_default_memory_request: 100Mi
    connection_pooler_image: repo.int.company.com/registry.opensource.zalan.do/acid/pgbouncer:master-7
    connection_pooler_max_db_connections: 60
    connection_pooler_mode: transaction
    connection_pooler_number_of_instances: 2
    connection_pooler_schema: pooler
    connection_pooler_user: pooler
  debug:
    debug_logging: true
    enable_database_access: true
  docker_image: repo.int.company.com/registry.opensource.zalan.do/acid/spilo-12:1.6-p3
  enable_crd_validation: true
  enable_lazy_spilo_upgrade: false
  enable_shm_volume: true
  etcd_host: ""
  kubernetes:
    cluster_domain: k8s.int.company.com
    cluster_labels:
      application: spilo
    cluster_name_label: k8s
    enable_init_containers: true
    enable_pod_antiaffinity: true
    enable_pod_disruption_budget: true
    enable_sidecars: true
    oauth_token_secret_name: postgres-operator
    pdb_name_format: postgres-{cluster}-pdb
    pod_antiaffinity_topology_key: failure-domain.beta.kubernetes.io/zone
    pod_management_policy: parallel
    pod_role_label: spilo-role
    pod_service_account_name: postgres-pod
    pod_terminate_grace_period: 5m
    secret_name_template: '{username}.{cluster}.credentials.{tprkind}.{tprgroup}'
    spilo_privileged: false
    watched_namespace: '*'
  load_balancer:
    db_hosted_zone: db.example.com
    enable_master_load_balancer: false
    enable_replica_load_balancer: false
    master_dns_name_format: '{cluster}.{team}.{hostedzone}'
    replica_dns_name_format: '{cluster}-repl.{team}.{hostedzone}'
  logging_rest_api:
    api_port: 8080
    cluster_history_entries: 1000
    ring_log_lines: 100
  logical_backup:
    logical_backup_docker_image: repo.int.company.com/registry.opensource.zalan.do/acid/logical-backup:latest
    logical_backup_s3_access_key_id: ""
    logical_backup_s3_bucket: my-bucket-url
    logical_backup_s3_endpoint: ""
    logical_backup_s3_region: ""
    logical_backup_s3_secret_access_key: ""
    logical_backup_s3_sse: AES256
    logical_backup_schedule: 30 00 * * *
  max_instances: -1
  min_instances: -1
  postgres_pod_resources:
    default_cpu_limit: "8"
    default_cpu_request: 500m
    default_memory_limit: 4096Mi
    default_memory_request: 1024Mi
    min_cpu_limit: 250m
    min_memory_limit: 250Mi
  repair_period: 5m
  resync_period: 30m
  teams_api:
    enable_teams_api: false
  timeouts:
    pod_deletion_wait_timeout: 10m
    pod_label_wait_timeout: 10m
    ready_wait_interval: 3s
    ready_wait_timeout: 30s
    resource_check_interval: 3s
    resource_check_timeout: 10m
  users:
    replication_username: standby
    super_username: postgres
  workers: 4
```

**Comment by FxKu** [comment]
Ok, then I think, it's in fact an issue that we do not define certain default values for CRD configuration and not related to the roles your manifest. The spilo image comes with an `admin` role as well a `zalandos` group role which we use for PAM authentication for employees.

When using the ConfigMap internal [defaults](https://github.com/zalando/postgres-operator/blob/master/pkg/util/config/config.go#L57) are set. However, when using CRD-config, values from the OperatorConfiguration are passed to this config struct and we have to check for empty values. We are already doing it for a couple of fields, but not for teams API options, where this PAM role is [defined](https://github.com/zalando/postgres-operator/blob/master/pkg/controller/operator_config.go#L138).

Can you try to define it in your manifest like we have it in our [example](https://github.com/zalando/postgres-operator/blob/master/manifests/postgresql-operator-default-configuration.yaml#L111)? Likely this issue wasn't raised until now, because people use this example manifest.

**Comment by stephan2012** [comment]
Thanks for the pointer, looks good now:

```
2020-05-22 08:06:21,947 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
2020-05-22 08:06:21,953 - bootstrapping - INFO - Could not connect to 169.254.169.254, assuming local Docker setup
2020-05-22 08:06:21,954 - bootstrapping - INFO - No meta-data available for this provider
2020-05-22 08:06:21,954 - bootstrapping - INFO - Looks like your running local
2020-05-22 08:06:21,984 - bootstrapping - INFO - Configuring wal-e
2020-05-22 08:06:21,985 - bootstrapping - INFO - Configuring pgbouncer
2020-05-22 08:06:21,985 - bootstrapping - INFO - No PGBOUNCER_CONFIGURATION was specified, skipping
2020-05-22 08:06:21,985 - bootstrapping - INFO - Configuring standby-cluster
2020-05-22 08:06:21,985 - bootstrapping - INFO - Configuring pam-oauth2
2020-05-22 08:06:21,985 - bootstrapping - INFO - No PAM_OAUTH2 configuration was specified, skipping
2020-05-22 08:06:21,985 - bootstrapping - INFO - Configuring log
2020-05-22 08:06:21,985 - bootstrapping - INFO - Configuring patroni
2020-05-22 08:06:21,994 - bootstrapping - INFO - Writing to file /home/postgres/postgres.yml
2020-05-22 08:06:21,994 - bootstrapping - INFO - Configuring certificate
2020-05-22 08:06:21,994 - bootstrapping - INFO - Generating ssl certificate
2020-05-22 08:06:22,139 - bootstrapping - INFO - Configuring pgqd
2020-05-22 08:06:22,139 - bootstrapping - INFO - Configuring crontab
2020-05-22 08:06:22,140 - bootstrapping - INFO - Skipping creation of renice cron job due to lack of SYS_NICE capability
2020-05-22 08:06:22,140 - bootstrapping - INFO - Configuring bootstrap
2020-05-22 08:06:23,529 INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-05-22 08:06:23,532 INFO: Lock owner: None; I am acid-minimal-test9-0
2020-05-22 08:06:23,573 INFO: trying to bootstrap a new cluster
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are enabled.

creating directory /home/postgres/pgdata/pgroot/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    /usr/lib/postgresql/11/bin/pg_ctl -D /home/postgres/pgdata/pgroot/data -l logfile start

2020-05-22 08:06:24 UTC [77]: [1-1] 5ec78800.4d 0     LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...
2020-05-22 08:06:24 UTC [77]: [2-1] 5ec78800.4d 0     LOG:  pg_stat_kcache.linux_hz is set to 500000
2020-05-22 08:06:24 UTC [77]: [3-1] 5ec78800.4d 0     LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-05-22 08:06:24 UTC [77]: [4-1] 5ec78800.4d 0     LOG:  listening on IPv6 address "::", port 5432
2020-05-22 08:06:24 UTC [77]: [5-1] 5ec78800.4d 0     LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-05-22 08:06:24,809 INFO: postmaster pid=77
2020-05-22 08:06:24 UTC [77]: [6-1] 5ec78800.4d 0     LOG:  redirecting log output to logging collector process
2020-05-22 08:06:24 UTC [77]: [7-1] 5ec78800.4d 0     HINT:  Future log output will appear in directory "../pg_log".
/var/run/postgresql:5432 - rejecting connections
/var/run/postgresql:5432 - rejecting connections
/var/run/postgresql:5432 - accepting connections
2020-05-22 08:06:25,867 INFO: establishing a new patroni connection to the postgres cluster
2020-05-22 08:06:25,882 INFO: running post_bootstrap
SET
DO
DO
DO
CREATE EXTENSION
NOTICE:  version "1.0" of extension "pg_auth_mon" is already installed
ALTER EXTENSION
GRANT
CREATE EXTENSION
NOTICE:  version "1.2" of extension "pg_cron" is already installed
ALTER EXTENSION
ALTER POLICY
REVOKE
GRANT
GRANT
CREATE FUNCTION
REVOKE
GRANT
REVOKE
GRANT
REVOKE
GRANT
GRANT
CREATE EXTENSION
DO
CREATE TABLE
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ALTER VIEW
GRANT
RESET
SET
NOTICE:  schema "zmon_utils" does not exist, skipping
DROP SCHEMA
DO
NOTICE:  language "plpythonu" does not exist, skipping
DROP LANGUAGE
NOTICE:  function plpython_call_handler() does not exist, skipping
DROP FUNCTION
NOTICE:  function plpython_inline_handler(internal) does not exist, skipping
DROP FUNCTION
NOTICE:  function plpython_validator(oid) does not exist, skipping
DROP FUNCTION
CREATE SCHEMA
GRANT
SET
CREATE TYPE
CREATE FUNCTION
CREATE FUNCTION
GRANT
You are now connected to database "postgres" as user "postgres".
CREATE SCHEMA
GRANT
SET
CREATE FUNCTION
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
GRANT
RESET
CREATE EXTENSION
CREATE EXTENSION
CREATE EXTENSION
NOTICE:  version "1.6" of extension "set_user" is already installed
ALTER EXTENSION
GRANT
GRANT
CREATE SCHEMA
GRANT
GRANT
SET
CREATE FUNCTION
REVOKE
GRANT
GRANT
CREATE VIEW
REVOKE
GRANT
GRANT
CREATE FUNCTION
REVOKE
GRANT
GRANT
CREATE VIEW
REVOKE
GRANT
GRANT
CREATE FUNCTION
REVOKE
GRANT
GRANT
CREATE VIEW
REVOKE
GRANT
GRANT
RESET
You are now connected to database "template1" as user "postgres".
CREATE SCHEMA
GRANT
SET
CREATE FUNCTION
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
CREATE FUNCTION
REVOKE
GRANT
COMMENT
GRANT
RESET
CREATE EXTENSION
CREATE EXTENSION
CREATE EXTENSION
NOTICE:  version "1.6" of extension "set_user" is already installed
ALTER EXTENSION
GRANT
GRANT
CREATE SCHEMA
GRANT
GRANT
SET
CREATE FUNCTION
REVOKE
GRANT
GRANT
CREATE VIEW
REVOKE
GRANT
GRANT
CREATE FUNCTION
REVOKE
GRANT
GRANT
CREATE VIEW
REVOKE
GRANT
GRANT
CREATE FUNCTION
REVOKE
GRANT
GRANT
CREATE VIEW
REVOKE
GRANT
GRANT
RESET
2020-05-22 08:06:26,601 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
2020-05-22 08:06:26,734 INFO: initialized a new cluster
```

I have filled in the values from the example:

```yaml
  teams_api:
    enable_team_superuser: false
    enable_teams_api: false
    pam_role_name: zalandos
    protected_role_names:
    - admin
    team_admin_role: admin
    team_api_role_configuration:
      log_statement: all
```

Maybe it is an option to simply add defaults to the Helm chart until the operator checks for empty fields because my operator config was generated straight from the chart.
